### PR TITLE
Fix #1272, #488 browse jdbc table for different databases

### LINKED ISSUE #1272: Browse JDBC "Number of rows only" does not display number of rows
**Describe the bug**
When using Browse JDBC with the option "Number of rows only" checked, the number of rows is not actually shown. It shows all columns in the table, but no results are displayed because there is no column for the ROWCOUNTER that should contain the COUNT(*)

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Console

**To Reproduce**
1. Go to 'Browse tables'
2. Check 'Number of rows only' and fill in the other fields
3. Press send
3. Scroll down to 'result'
4. See no result shown

**Expected behavior**
The number of rows to be displayed.

**Screenshots**
image

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Websphere
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6-20201113.112750

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by alisihab**

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/webcontrol/api/BrowseJdbcTable.java [hunk 1]
```diff
@@ -134,32 +136,58 @@ public Response execute(LinkedHashMap<String, Object> json) throws ApiException
...
+					String field = null;
+					if(!numberOfRowsOnly) {
+						field = "<field name=\""+rnumColumnName+"\" type=\"INTEGER\" />";
+						fielddefinition.append(field);
+						fieldDef.put(rnumColumnName, "INTEGER");
+						while(rs.next()) {
+							field = "<field name=\"" + rs.getString(4) + "\" type=\"" + DB2XMLWriter.getFieldType(rs.getInt(5)) + "\" size=\"" + rs.getInt(7) + "\"/>";
+							fielddefinition.append(field);
+							fieldDef.put(rs.getString(4), DB2XMLWriter.getFieldType(rs.getInt(5)) + "("+rs.getInt(7)+")");
+						}
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/webcontrol/api/BrowseJdbcTable.java:155]: Would it be possibe to use descriptive constants or column names, instead of '4', '5' and '7'?

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

**Review by gvanbrakel — APPROVED** [review]

**Review by nielsm5 — APPROVED** [review]
