### PR TITLE
Throw exception when file to read does not exist in fileSystems (7.7)

### LINKED ISSUE #3266: LocalFileSystemPipe does not follow exception forward
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
FilePipe in a frank is replaced by a localFilesystemPipe. In a larva scenario, it is expected to throw an exception since the file does not exists. However, when base64 attribute is not present in the pipe configuration pipeline does not follow exception forward. On the other hand, with base64 attribute being set to encode it follows exception forward.

**Reporter**
Laura

FF 7.7.1 not tested with the latest

### PR DESCRIPTION
**Pull request by alisihab**
Closes #3266

### CODE REVIEW

**Review by nielsm5 — APPROVED** [review]

File: core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemActor.java [hunk 1]
```diff
@@ -336,6 +336,9 @@ public Object doAction(Message input, ParameterValueList pvl, PipeLineSession se
 				}
 				case READ: {
 					F file=getFile(input, pvl);
+					if(!fileSystem.exists(file)) {
+						throw new FileSystemException("File to read does not exist.");
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/filesystem/FileSystemActor.java:340]: It would be good to include the filename in the error message

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

**Review by gvanbrakel — APPROVED** [review]
