### PR TITLE
response mapping for all non empty exits in open api

### LINKED ISSUE #1093: OpenAPI schema error responses have no schema information
**Describe the bug**
When having an adapter with an Json2XmlValidator-InputValidator, configured with both root and responseRoot to get the OpenAPI schema generated, only the success exit gets schema defintions. Any error exits do not get schema defintions, but only:

`"500":{
	"description":"Internal Server Error",
	"content":{
		"application/json":{
		}
	}
}`

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Console
 - Frank Framework

**To Reproduce**
1. I think description is clear enough, if project files are required contact me.

**Expected behavior**
For the error exits to also have correct schema definitions. I think the validators should also have an "errorRoot" attribute to separate OK responses from NOK responses in generated schemas. This attribute should default to the normal responseRoot attribute.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Tomcat
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6-20200909.154756

**Additional context**
N/A

### LINKED ISSUE #1096: OpenAPI schema inputs have no schema information
**Describe the bug**
Inputs for ApiListeners do not have information in the generated OpenAPI schema. For parameters in the uriPattern only * is shown in the path without the restrictions that follow from the inputvalidator, for POST nothing is shown.

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Console
 - Frank Framework

**To Reproduce**
1. I think description is clear enough, if project files are required contact me.

**Expected behavior**
To also see input-related restrictions in the generated schema

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Tomcat
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6-20200909.154756

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by alisihab**
Fixes #1093 
Fixes #1096

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java [hunk 1]
```diff
@@ -242,6 +242,8 @@ private JsonObjectBuilder mapResponses(IAdapter adapter, MediaTypes contentType,
 				if(schema == null) {
 					content.addNull(contentType.getContentType());
 				} else {
+					// JsonObjectBuilder add method consumes the schema
+					schema.add("schema", Json.createObjectBuilder().add("$ref", "#/components/schemas/"+ref));
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java:246]: What is ref is `null`?

**Review by nielsm5 — CHANGES_REQUESTED** [review]
Does this not break any tests? Perhaps we should consider making one!

File: core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java [hunk 2]
```diff
@@ -180,7 +180,12 @@ protected JsonObject generateOpenApiJsonSchema(Collection<ApiDispatchConfig> cli
...
 					methodBuilder.add("operationId", adapter.getName());
-
+					PipeLine pipeline = adapter.getPipeLine();
+					Json2XmlValidator validator = getJsonValidator(pipeline);
+					if(validator != null && StringUtils.isNotEmpty(validator.getRoot())) {
+						MediaTypes consumes = MediaTypes.valueOf(listener.getConsumes());
+						methodBuilder.add("requestBody", mapRequest(consumes, validator.getRoot()));
+					}
 					//ContentType may have more parameters such as charset and formdata-boundry
 					MediaTypes produces = MediaTypes.valueOf(listener.getProduces());
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java:190]: In the spirit of 'we want enums', could you refactor the ApiListener a bit?
Replace the `getProduces()` and `getConsumes` with `getProducesEnum()` and `getConsumesEnum`. So you don't have to convert the strings back to enums on line 186 and 190?

**Review by nielsm5 — CHANGES_REQUESTED** [review]

**Review by nielsm5 — APPROVED** [review]
