### PR TITLE
Fix #1256 configure receivers even if pipeline fails to configure

### LINKED ISSUE #1256: Cannot determine number of messages in errorstore, NullPointerException
**Describe the bug**
The ibis4titan.log files show a lot these nullpointerExceptions:

2020-11-11 09:03:27,344 WARN [WebContainer : 7] null api.ShowConfigurationStatus - Cannot determine number of messages in errorstore
nl.nn.adapterframework.core.ListenerException: cannot determine message count: (NullPointerException)

**Reporter**
Richard van der Stel

**Category** 
 - Frank Console
 - Frank Framework

**To Reproduce**
1. Go to logging
2. Click on ibis4titan.log
3. Scroll down to nullpointerException

**Expected behavior**
no nullpointers

**Screenshots**
see attachment for stacktrace

**Environment:**
 - Application server Websphere
 - Browser n.a.
 - IAF Version : FF! 7.6-20201110.095003

**Additional context**
see attachment for stacktrace
[NullPointerException.txt](https://github.com/ibissource/iaf/files/5522717/NullPointerException.txt)

### PR DESCRIPTION
**Pull request by alisihab**
Fixes #1256

### CODE REVIEW

**Review by gvanbrakel — APPROVED** [review]

File: core/src/main/java/nl/nn/adapterframework/core/PipeLine.java [hunk 1]
```diff
@@ -396,10 +396,7 @@ public void configure(IPipe pipe) throws ConfigurationException {
 			pipeStatistics.put(pipe.getName(), new StatisticsKeeper(pipe.getName()));
 			//congestionSensors.addSensor(pipe);
 		} catch (Throwable t) {
-			if (t instanceof ConfigurationException) {
-				throw (ConfigurationException)t;
-			}
-			throw new ConfigurationException("Exception configuring Pipe ["+pipe.getName()+"]",t);
+			throw new ConfigurationException("Exception configuring "+ ClassUtils.nameOf(pipe) +" ["+pipe.getName()+"]",t);
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/core/PipeLine.java:399]: Could you check other locations where pipes are configured, like for validators and wrappers, to see the same extension to the exception message is made?

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

File: core/src/main/java/nl/nn/adapterframework/core/PipeLine.java (hunk 1 above)
Comment (gvanbrakel) [reply core/src/main/java/nl/nn/adapterframework/core/PipeLine.java:399]: You just showed me it is already done!

**Review by gvanbrakel — APPROVED** [review]

**Review by nielsm5 — APPROVED** [review]
