### PR TITLE
Fix splitting requestUrl in openApi schema generation

### LINKED ISSUE #3290: OpenApi generator fails with PatternSyntaxException
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When clicking on the OpenAPI 3.0 button, an error message is shown : 
java.util.regex.PatternSyntaxException: Illegal repetition near index 27
/ts/openarchive/attachments/{documentId}/ts_openarchive_attachments_{documentId}_GET_openapi.json

In version 7.6.3 this works without any issues, the uriPattern is not changed.

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**
image

**Configuration**
Adapter.xml send via email to Gerrit+Niels

**Input**
stacktrace and more info send via email to Gerrit+Niels

**Environment**
FF! 7.7.1

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**

### PR DESCRIPTION
**Pull request by alisihab**
Closes #3290

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java [hunk 1]
```diff
@@ -232,11 +233,11 @@ private JsonArrayBuilder mapServers(HttpServletRequest request) {
 		String loadBalancerUrl = AppConstants.getInstance().getProperty("loadBalancer.url", null);
 		if(StringUtils.isNotEmpty(loadBalancerUrl)) {
 			serversArray.add(Json.createObjectBuilder().add("url", loadBalancerUrl + servletPath).add("description", "load balancer"));
-		}
-		else { // fall back to the request url
+		} else { // fall back to the request url
 			String requestUrl = request.getRequestURL().toString(); // -> schema+hostname+port/context-path/servlet-path/+request-uri
+			requestUrl = Misc.urlDecode(requestUrl); // request url from browser might be encoded
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java:238]: I assume this solves the problem? It would be wise to include a test using an encoded requestUrl

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

**Review by gvanbrakel — APPROVED** [review]

**Review by nielsm5 — COMMENTED** [review]
It's just the request url that's giving issues, there is no need to display/put the curly braces in the url. I also noticed the url contains the path twice? See `hello-world/hello-world_GET_openapi.json` maybe that can also be simplified? Unless I'm missing something here, I feel like this solution is making it more complex that it shoud be, escaping the url will make it less readable, see `hello-world/%7Bmy-var%7D/hello-world_%7Bmy-var%7D_GET_openapi.json`

File: core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java [hunk 2]
```diff
@@ -54,6 +54,7 @@
 import nl.nn.adapterframework.util.AppConstants;
 import nl.nn.adapterframework.util.DateUtils;
 import nl.nn.adapterframework.util.LogUtil;
+import nl.nn.credentialprovider.util.Misc;
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/http/rest/ApiServiceDispatcher.java:57]: could you correct the packagename?

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

**Review by gvanbrakel — APPROVED** [review]
