### PR TITLE
Fix #1026 Fix exception overriding in webservice sender

### LINKED ISSUE #1026: WebServiceSender-multipart response without file
**Describe the bug**
In some cases a response from the WebServiceListener to a WebServiceSender is required to be in multipart format, even when there are no files/parts to be returned. It appears that in either the WebServiceListener or the WebServiceSender this work not properly for the case that there is no file.

**Reporter**
Ali

**Category** 
Use following Tags to categorize your bug report
 - Frank Console
 - Frank Framework
* - Ladybug (debugging tool) --> also is a separate project with own issues*
 - Larva (unit test tool)
 - Performance

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty)
 - IAF Version [e.g. 7.5 RC3, 7.6]

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

### PR DESCRIPTION
**Pull request by alisihab**
- multipartResponse attribute will be deprecated. Responses with a 'multipart/*' content-type will be detected automatically.
Fixes #1026

### CODE REVIEW

File: core/src/test/java/nl/nn/adapterframework/http/WebServiceSenderResultTest.java [hunk 1]
```diff
@@ -0,0 +1,202 @@
...
+		this.sender = sender;
+		return sender;
+	}
+
+	public WebServiceSender createWebServiceSenderFromFile(String testFile, int statusCode) throws IOException {
+		InputStream file = getFile(testFile);
+		byte[] fileArray = Misc.streamToBytes(file);
+		String contentType = null;
+
+		BufferedReader reader = new BufferedReader(new InputStreamReader(new ByteArrayInputStream(fileArray)));
```
Comment (nielsm5) [inline core/src/test/java/nl/nn/adapterframework/http/WebServiceSenderResultTest.java:94]: What is happening here? an inputstream to bytearray to inputstream to reader?

File: core/src/test/java/nl/nn/adapterframework/http/WebServiceSenderResultTest.java [hunk 2]
```diff
@@ -0,0 +1,202 @@
...
+import nl.nn.adapterframework.util.Misc;
+
+public class WebServiceSenderResultTest extends Mockito {
+
+	@Rule
+	public ExpectedException thrown = ExpectedException.none();
+
+	private WebServiceSender sender = null;
+
+	public WebServiceSender createWebSeriveSender(InputStream responseStream, String contentType, int statusCode) throws IOException {
```
Comment (nielsm5) [inline core/src/test/java/nl/nn/adapterframework/http/WebServiceSenderResultTest.java:56]: createWebSeriveSender should be createWebServiceSender

**Review by nielsm5 — CHANGES_REQUESTED** [review]

File: core/src/main/java/nl/nn/adapterframework/http/HttpSender.java [hunk 3]
```diff
@@ -577,7 +583,16 @@ public String getResponseBodyAsString(HttpResponseHandler responseHandler) throw
...
 		}
-		String responseBody = responseHandler.getResponseAsString(true);
+		String responseBody = null;
+		try {
+			responseBody = responseHandler.getResponseAsString(true);
+		} catch(IOException e) {
+			if(throwIOExceptionWhenParsingResponse) {
+				throw e;
+			}
+			return null;
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/http/HttpSender.java:593]: And what happens to the exception then? It's just gone?
At least log it!

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

File: core/src/main/java/nl/nn/adapterframework/http/HttpSender.java (hunk 3 above)
Comment (alisihab) [reply core/src/main/java/nl/nn/adapterframework/http/HttpSender.java:593]: This method will be called in case of an exception. The exception thrown by this method is not the actual cause. Therefore, it can be ignored. The caller methods will throw the actual exception

Comment (nielsm5) [reply core/src/main/java/nl/nn/adapterframework/http/HttpSender.java:593]: I think it would be wise to add a comment describing the problem. Either near the try/catch or as javadoc above the method.

When an exception occurs and the response cannot be parsed, we do not want to throw a 'missing response' exception. Since this method is used when handling other exceptions (link to wss exception here) (link to http exception here), silently return null, to avoid npe's, ioexceptions etc.

**Review by nielsm5 — APPROVED** [review]

**Review by gvanbrakel — APPROVED** [review]
