### PR TITLE
Format only xml like text in larva comparison

### LINKED ISSUE #1790: Larva cannot compare json files
**Describe the issue**
Larva cannot compare json files. When you try to, both screens of the comparison become empty.

**Reporter**
Gerrit

**To Reproduce**
1. Go to iaf-test
2. Modify expected response file  /iaf-test/src/test/testtool/Validators/Schema/openapi_post.json (to make the test fail)
2. Run scenario \Validators\Json2XmlValidator\scenario26 - API POST OpenApi-schema
3. Click 'compare' to see the differences
4. See that 'result' and 'expected' become empty.

**Screenshots**

**Configuration**
```
scenario.description = API POST OpenApi-schema

include = common.properties

step1.api.Json2XmlValidatorSchema_post.write = ../Schema/get-openapi.txt
step2.api.Json2XmlValidatorSchema_post.read  = ../Schema/openapi_post.json

ignoreContentBetweenKeys1.key1="servers":[
ignoreContentBetweenKeys1.key2=]
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7-SNAPSHOT: Ibis4Test
Running on LPZWNL000040524 using Apache Tomcat/9.0.43
Java Version: OpenJDK Runtime Environment (1.8.0_41-b04)
Heap size: 173M, total JVM memory: 247M
Free disk space: 291GB, total disk space: 476GB
Up since: 2021-05-10 09:27:39 (41m)
```

**Additional Environment**
 - Browser: Chrome

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

### PR DESCRIPTION
**Pull request by alisihab**
Closes #1790

### CODE REVIEW

File: webapp/src/main/webapp/larva/assets/lib.js [hunk 1]
```diff
@@ -396,9 +396,13 @@ function indentCompare(sources, result)
 {
 	var s = eval(sources);
 	
-	for (var i = 0; i < s.length; i++)
-		xmlFormat(s[i]);
-		
+	for (var i = 0; i < s.length; i++){
+		// if it is xml
```
Comment (nielsm5) [inline webapp/src/main/webapp/larva/assets/lib.js:400]: Since you're fetching `s[i]` 3 times, it might perform better if you assign the value first;
`var j = s[i];`

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

File: webapp/src/main/webapp/larva/assets/lib.js [hunk 2]
```diff
@@ -396,9 +401,17 @@ function indentCompare(sources, result)
 {
 	var s = eval(sources);
 	
-	for (var i = 0; i < s.length; i++)
-		xmlFormat(s[i]);
-		
+	for (var i = 0; i < s.length; i++){
+		var elementId = s[i];
+		var text = $(elementId).value;
```
Comment (nielsm5) [inline webapp/src/main/webapp/larva/assets/lib.js:406]: Can this be moved to the `jsonFormat` ?

**Review by nielsm5 — CHANGES_REQUESTED** [review]

**Review by nielsm5 — APPROVED** [review]

File: webapp/src/main/webapp/larva/assets/lib.js [hunk 3]
```diff
@@ -396,9 +402,17 @@ function indentCompare(sources, result)
...
+		// if text is xml
+		if(text.startsWith("<") || text.startsWith(escapeChars("<"))){
+			xmlFormat(elementId);
+		} else if ((text.startsWith("{") && text.endsWith("}")) || (text.startsWith("[") && text.endsWith("]"))) { // TODO: something smarter for detecting json like text
+			jsonFormat(elementId);
+		}
```
Comment (gvanbrakel) [inline webapp/src/main/webapp/larva/assets/lib.js:413]: When the formatting fails, e.g. due to a syntax error, something like the original text should be displayed.

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

**Review by gvanbrakel — APPROVED** [review]
