### PR TITLE
Fix #958 Handle returned exitState in IbisLocalSender

### LINKED ISSUE #958: ForEachChildElementPipe does not show error causes properly
**Describe the bug**
When an error occurs in a subadapter of a ForEachChildElementPipe, the cause is not properly shown in the errormessage of the ForEachChildElementPipe, neither when thrown as exception, or as exit-state!=success. 
Sometimes only an empty \<block/\> is returned. 

**Reporter**
Bastiaan/Ali

**Category**
 - Frank Framework

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - IAF Version [7.6 d.d. 21-7-2020]

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

### PR DESCRIPTION
**Pull request by gvanbrakel**

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/receivers/ReceiverBase.java [hunk 1]
```diff
@@ -184,6 +184,8 @@
 	public static final String ONERROR_CONTINUE = "continue";
 	public static final String ONERROR_RECOVER = "recover";
 	public static final String ONERROR_CLOSE = "close";
+	
+	public static final String EXIT_STATE_CONTEXT_KEY="exitState";
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/receivers/ReceiverBase.java:188]: Deze moet naar de IPipeLineSession

File: core/src/main/java/nl/nn/adapterframework/webcontrol/api/ServerStatistics.java [hunk 2]
```diff
@@ -312,8 +312,9 @@ public Response updateLogConfiguration(LinkedHashMap<String, Object> json) throw
 				Level loglevel = Level.toLevel(""+value, null);
 				Logger rootLogger = LogUtil.getRootLogger();
 				if(loglevel != null && rootLogger.getLevel() != loglevel) {
+					String changmsg = "LogLevel changed from [" + rootLogger.getLevel() + "] to [" + loglevel +"]";
 					Configurator.setLevel(rootLogger.getName(), loglevel);
-					msg.append("LogLevel changed from [" + rootLogger.getLevel() + "] to [" + loglevel +"]");
+					msg.append(changmsg);
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/webcontrol/api/ServerStatistics.java:317]: ?

**Review by nielsm5 — CHANGES_REQUESTED** [review]

File: core/src/main/java/nl/nn/adapterframework/webcontrol/api/ServerStatistics.java (hunk 2 above)
Comment (gvanbrakel) [reply core/src/main/java/nl/nn/adapterframework/webcontrol/api/ServerStatistics.java:317]: In de oude situatie was de 'from' al veranderd.
Er stond dan: LogLevel changed from [DEBUG] to [DEBUG]

**Review by nielsm5 — APPROVED** [review]
