### PR TITLE
Log warning when cleaning IBISLOCK

### LINKED ISSUE #2125: Log warning/error when cleaning IBISLOCK
**Describe the issue**
The IBISLOCK table is used to register locks for processes that only should run once at a time. When such a (temporary) lock is removed by the cleanup, this is usually an indication something is going wrong (process running to long or has been interrupted). Now these locks are cleaned up silently. I would like to request that an error is logged when temporary locks are cleaned up to inform users that there might be a problem that needs to be investigated.

**Reporter**
Please state your name. If we don't know who is reporting, a solution of the issue might be delayed.

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

### PR DESCRIPTION
**Pull request by alisihab**
Closes #2125

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/scheduler/JobDef.java [hunk 1]
```diff
@@ -699,7 +700,11 @@ private void cleanupDatabase(IbisManager ibisManager) {
 				qs.open();
 
 				Message result = qs.sendMessage(Message.nullMessage(), null);
-				log.info("result [" + result + "]");
+				String resultString = result.asString();
+				int numberOfRowsAffected = Integer.valueOf(resultString);
+				if(numberOfRowsAffected > 0) {
+					log.warn("deleted ["+numberOfRowsAffected+"] row(s) from [IBISLOCK] table. It implies that there had been some process(es) finished unexpectedly or failed to complete. Please investigate the log files!");
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/scheduler/JobDef.java:706]: Could you log this to the `getMessageKeeper` ?

File: core/src/main/java/nl/nn/adapterframework/scheduler/JobDef.java [hunk 2]
```diff
@@ -699,7 +700,11 @@ private void cleanupDatabase(IbisManager ibisManager) {
 				qs.open();
 
 				Message result = qs.sendMessage(Message.nullMessage(), null);
-				log.info("result [" + result + "]");
+				String resultString = result.asString();
+				int numberOfRowsAffected = Integer.valueOf(resultString);
+				if(numberOfRowsAffected > 0) {
+					getMessageKeeper().add("deleted ["+numberOfRowsAffected+"] row(s) from [IBISLOCK] table. It implies that there had been some process(es) finished unexpectedly or failed to complete. Please investigate the log files!", MessageKeeperLevel.WARN);
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/scheduler/JobDef.java:706]: It implies that there have been process(es) that finished unexpectedly or failed to complete.

**Review by gvanbrakel — APPROVED** [review]
