### PR TITLE
fix test scenarios to create required folder automatically

### LINKED ISSUE #1065: FxF3 scenarios 1 and 2 fail
**Describe the bug**
In Ibis4Test, FxF3 scenarios 1 and 2 fail. For scenario 1, this happens because a FileWrapperPipe is used. The configure method of this pipe checks whether the value of property "fxf.dir" is an existing directory. This is not expected to be the case in the Larva tests of Ibis4Test. The value of this property is c:\temp\testdata\fxf under Windows. This directory should be created during the execution of the Larva tests.

**Reporter**
Martijn Dirkse

**Category** 
 - Frank Framework

**To Reproduce**
1. Ensure that directory c:\temp\testdata\fxf does not exist.
2. Restart Ibis4Test
3. Go to Larva.
4. Run scenario FxF3\scenario01

**Expected behavior**
The tests should succeed.

**Screenshots**

**Environment:**
 - Windows, working with Eclipse and an Eclipse-managed Tomcat server.
 - Microsoft Edge
 - Commit 9c707e7dbdf48e59e1a50cb03ae44776c8c9b3bf

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

### PR DESCRIPTION
**Pull request by alisihab**
- rename checkDirectory to assumeDirectoryExists in UnzipPipe
- Introduce a createFolder attribute in FxfWrapperPipe to create the fxf.dir folder in case it does not exists
- fix unzip exception forward test scenario to create unzip folder at the beginning
Fixes #1065

### CODE REVIEW

**Comment by mhdirkse** [comment]
Thanks for this pull request, Ali

File: core/src/main/java/nl/nn/adapterframework/pipes/UnzipPipe.java [hunk 1]
```diff
@@ -337,14 +337,12 @@ public void setCreateSubdirectories(boolean b) {
...
 	}
-	
-	@IbisDoc({"if set <code>true</code>, validation on directory is ignored", "false"})
-	public boolean isCheckDirectory()
-	{
-		return checkDirectory;
+
+	@IbisDoc({"if set <code>true</code>, validation of directory is ignored", "false"})
+	public boolean isAssumeDirectoryExists() {
+		return assumeDirectoryExists;
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/pipes/UnzipPipe.java:343]: Could you:
- set the setter before the getter, with the ibisdoc before the setter
- make a setCheckDirectory() with \@Deprecated, and a config warning stating what you did

File: test/src/main/configurations/MainConfig/ConfigurationUnzip.xml [hunk 2]
```diff
@@ -6,9 +6,16 @@
 			serviceName="ibis4test-ZipFilePathListener" />
 	</Receiver>
 
-	<Pipeline firstPipe="unzipFile">
+	<Pipeline firstPipe="createOutputFolder">
```
Comment (gvanbrakel) [inline test/src/main/configurations/MainConfig/ConfigurationUnzip.xml:9]: if the firstPipe is the first pipe, it is not necessary to configure it, so then you can remove the attribute

File: core/src/main/java/nl/nn/adapterframework/extensions/fxf/FxfWrapperPipe.java [hunk 3]
```diff
@@ -305,4 +313,12 @@ public void setFxfVersion(String fxfVersion) {
 	public String getFxfVersion() {
 		return fxfVersion;
 	}
+
+	public boolean isCreateFolder() {
+		return createFolder;
+	}
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/extensions/fxf/FxfWrapperPipe.java:319]: Could you place the getter after the setter?

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

**Review by gvanbrakel — APPROVED** [review]

File: core/src/main/java/nl/nn/adapterframework/extensions/fxf/FxfWrapperPipe.java [hunk 4]
```diff
@@ -117,7 +119,11 @@ public void configure() throws ConfigurationException {
 			fxfDir = AppConstants.getInstance(getConfigurationClassLoader()).getResolvedProperty("fxf.dir");
 			if (fxfDir == null) {
 				throw new ConfigurationException("property fxf.dir has not been initialised");
-			} else if (!new File(fxfDir).isDirectory()) {
+			}
+			if(isCreateFolder() && !new File(fxfDir).exists() && !new File(fxfDir).mkdirs()) {
+				throw new ConfigurationException(" Cannot create fxf.dir in the path '" + fxfDir + "'");
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/extensions/fxf/FxfWrapperPipe.java:124]: Could you please remove the space in front of could (lower case), put arguments between `[ ... ]` instead of `' ...  '`. And can you also change this in the ConfigurationException underneath?

**Review by nielsm5 — CHANGES_REQUESTED** [review]
Hey Ali, I've got a tiny remark, other then that its a go!
