### PR TITLE
Fix iaf-test validator openapi scenarios

### LINKED ISSUE #1545: iaf-test fails on OpenAPI schema generation
**Describe the bug**
Scenario '\Validators\Json2XmlValidator\scenario25 - API GET OpenApi-schema' failed
Scenario '\Validators\SoapValidator\scenario25 - API GET OpenApi-schema' failed

**Reporter**
Gerrit

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
1. Go to iaf-test
2. Run the specified scenarios
3. See error

**Expected behavior**
All scenarios pass

**Screenshots**

**Environment:**
 - Application server: Tomcat
 - DBMS: H2
 - Browser: Chrome
 - IAF Version: 7.6 snapshot d.d. 5-3-21

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

### PR DESCRIPTION
**Pull request by alisihab**
Fixes #1545

### CODE REVIEW

**Review by gvanbrakel — CHANGES_REQUESTED** [review]
Could you please also fix:
```
 java.lang.NullPointerException
 at nl.nn.adapterframework.http.rest.ApiServiceDispatcher.generateOpenApiJsonSchema(ApiServiceDispatcher.java:180)
 at nl.nn.adapterframework.http.rest.ApiServiceDispatcher.generateOpenApiJsonSchema(ApiServiceDispatcher.java:160)
 at nl.nn.adapterframework.http.rest.ApiListenerServlet.service(ApiListenerServlet.java:142)
```

File: core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java [hunk 1]
```diff
@@ -139,9 +139,11 @@ protected void service(HttpServletRequest request, HttpServletResponse response)
...
 			ApiDispatchConfig apiConfig = dispatcher.findConfigForUri(uri);
-			JsonObject jsonSchema = dispatcher.generateOpenApiJsonSchema(apiConfig);
-			returnJson(response, 200, jsonSchema);
-			return;
+			if(apiConfig != null) {
+				JsonObject jsonSchema = dispatcher.generateOpenApiJsonSchema(apiConfig);
+				returnJson(response, 200, jsonSchema);
+				return;
+			}
 		}
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java:147]: please add an error response in case no openapi.json can be returned because no matching config was found (apiConfig==null)

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

File: core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java (hunk 1 above)
Comment (alisihab) [reply core/src/main/java/nl/nn/adapterframework/http/rest/ApiListenerServlet.java:147]: error response is in line 161

**Review by gvanbrakel — APPROVED** [review]

**Review by nielsm5 — APPROVED** [review]
