### PR TITLE
Disable output validation for empty result exits

### LINKED ISSUE #1126: OutputValidator validates when exit empty="true"
**Describe the bug**
When forwarding to an exit with empty="true", validation of the message is still done even though nothing is send back to the calling application. To prevent errors, the message has to be transformed to something that is valid for the validator, which is an unnecessary step.

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
I think description is clear enough, if example configurations are needed, please contact me.

**Expected behavior**
Validator to be skipped for exits with empty="true"

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Tomcat
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6-20200909.154756

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by alisihab**
Fixes #1126

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/processors/CorePipeLineProcessor.java [hunk 1]
```diff
@@ -186,58 +186,62 @@ public PipeLineResult processPipeLine(PipeLine pipeLine, String messageId, Messa
...
-							PipeForward wrapForward=wrapResult.getPipeForward();
-							if (wrapForward.getPath()==null) {
-								throw new PipeRunException(pipeToRun,"forward ["+wrapForward.getName()+"] of outputWrapper has emtpy forward path");
-							}
-							log.warn("setting next pipe to ["+wrapForward.getPath()+"] due to wrap fault");
-							outputWrapError = true;
-							pipeToRun = pipeLine.getPipe(wrapForward.getPath());
-							if (pipeToRun==null) {
-								throw new PipeRunException(pipeToRun,"forward ["+wrapForward.getName()+"], path ["+wrapForward.getPath()+"] does not correspond to a pipe");
+					if(!plExit.getEmptyResult()) {
```
Comment (alisihab) [inline core/src/main/java/nl/nn/adapterframework/processors/CorePipeLineProcessor.java:189]: I don't know why it looks i changed a lot. I just added this check and corresponding else block.

**Review by gvanbrakel — APPROVED** [review]
