### PR TITLE
Fix #577 minor improvement while writing the lineseparator

### LINKED ISSUE #577: FilePipe writeLineSeparator writes newline in separate write action allowing other threads to write between output and newline
**Describe the bug**
Using writeLineSeparator in a multithreading adapter gave a invalid result
**result:** 
```
line1<Newline>
line2line3<Newline>
<Newline>
line4<Newline>
```

**expected result**
```
line1<Newline>
line2<Newline>
line3<Newline>
line4<Newline>
```

**Category**
 - Frank Framework

**To Reproduce**
- create an adapter writing in bulk to a file using multiple threads
- apply load

**Expected behavior**
By adding the newline to the string to write and write in 1 go this problem will no longer occur 

**Environment:**
 - websphere
 - IAF 7.5-20200124.165603

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

### PR DESCRIPTION
**Pull request by alisihab**

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/util/Misc.java [hunk 1]
```diff
@@ -205,14 +205,19 @@ public static void fileToStream(String filename, OutputStream output) throws IOE
...
+		streamToStream(input, output, true, null);
+	}
+	
+	public static void streamToStream(InputStream input, OutputStream output, boolean closeInput) throws IOException {
+		streamToStream(input, output, closeInput, null);
 	}
 
 	/**
 	 * Writes the content of an input stream to an output stream by copying the buffer of input stream to the buffer of the output stream.
+	 * If eof is specified, appends new line char after copying data.
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/util/Misc.java:220]: it appends the bytes specified in eof, (that could represent a newline)

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

**Review by gvanbrakel — APPROVED** [review]

**Review by nielsm5 — APPROVED** [review]
