### PR TITLE
Provide ability to follow exception forwards 

### LINKED ISSUE #516: Unzip pipe has no exception forward
**Describe the bug**
When an exception occurs unzipping, a PipeRunException is always thrown

**Category**
 - Frank Framework

**To Reproduce**
1. Unzip an invalid .zip file with the unzip pipe

**Expected behavior**
Configurable exception forward. Maybe a small wrapper class around FixedForward, to have this behaviour for more pipes

**Screenshots**

**Environment:**
 - IAF Version 7.5-RC2 and others.

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

### PR DESCRIPTION
**Pull request by alisihab**
Fixes #516

### CODE REVIEW

**Review by gvanbrakel — CHANGES_REQUESTED** [review]
The basics of the PR are good.
However, if you provide a test as 'Unzip', then you'll have to make a proper unzip test.
You could also choose to create a test of this functionality only, for instance using the Exception pipe.

File: core/src/main/java/nl/nn/adapterframework/processors/ExceptionHandlingPipeProcessor.java [hunk 1]
```diff
@@ -0,0 +1,51 @@
+/*
+   Copyright 2013, 2020 Nationale-Nederlanden
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/processors/ExceptionHandlingPipeProcessor.java:2]: `2020 WeAreFrank!`
Unless you made this in 2013?

File: core/src/main/java/nl/nn/adapterframework/processors/ExceptionHandlingPipeProcessor.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+import nl.nn.adapterframework.core.PipeRunResult;
+import nl.nn.adapterframework.errormessageformatters.ErrorMessageFormatter;
+import nl.nn.adapterframework.stream.Message;
+import nl.nn.adapterframework.util.DateUtils;
+
+public class ExceptionHandlingPipeProcessor extends PipeProcessorBase {
+
+	@Override
+	public PipeRunResult processPipe(PipeLine pipeLine, IPipe pipe, Message message, IPipeLineSession pipeLineSession)
+			throws PipeRunException {
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/processors/ExceptionHandlingPipeProcessor.java:34]: I would personally prefer if this would be on 1 line..

File: core/src/main/java/nl/nn/adapterframework/processors/ExceptionHandlingPipeProcessor.java [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+		PipeRunResult prr = null;
+		try {
+			prr = pipeProcessor.processPipe(pipeLine, pipe, message, pipeLineSession);
+		} catch (PipeRunException e) {
+			Map<String, PipeForward> forwards = pipe.getForwards();
+			if (forwards!=null && forwards.containsKey("exception")) {
+				long tsReceived = DateUtils.parseToDate((String) pipeLineSession.get(IPipeLineSession.tsReceivedKey), DateUtils.FORMAT_FULL_GENERIC).getTime();
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/processors/ExceptionHandlingPipeProcessor.java:41]: This session value is a drama, as we would say in Dutch. I believe it's possible for it to be either a `Date` or a formatted timestamp. Please look [here](https://github.com/ibissource/iaf/blob/master/core/src/main/java/nl/nn/adapterframework/receivers/ReceiverBase.java#L930)  for more info!

**Review by nielsm5 — CHANGES_REQUESTED** [review]

**Comment by gvanbrakel** [comment]
I see you placed the scenario01.properties and scenario02.properties inside the subdirectories scenario01 and scenario02. This is usually not done, so this might be confusing.

**Review by gvanbrakel — CHANGES_REQUESTED** [review]
One additional request: Could you document this feature in the javadoc of AbstractPipe?

**Review by nielsm5 — APPROVED** [review]

**Review by nielsm5 — APPROVED** [review]

**Review by gvanbrakel — APPROVED** [review]
