### PR TITLE
Fix LiquibaseScriptGenerator

### LINKED ISSUE #2518: Liquibase script generator in Frank!Console produces error on ibis4example
**Describe the issue**
When I browse to https://ibis4example.ibissource.org/ and run the Liquibase script generator, I see an error. See picture below:

image

I got this error after pressing the button "Generate SQL"

**Reporter**
Martijn Dirkse

**To Reproduce**
1. Browse to https://ibis4example.ibissource.org/.
2. Click JDBC | Liquibase Script.
3. Press "Generate SQL"

**Screenshots**
See above.

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Google Chrome.

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

### PR DESCRIPTION
**Pull request by alisihab**
Fixes #2518

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowLiquibaseScript.java [hunk 1]
```diff
@@ -79,7 +79,7 @@ public Response downloadScript() throws ApiException {
 
 		for(Configuration config : getIbisManager().getConfigurations()) {
 			DatabaseMigratorBase databaseMigrator = config.getBean("jdbcMigrator", DatabaseMigratorBase.class);
-			if(databaseMigrator.isEnabled()) {
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowLiquibaseScript.java:82]: I would personally prefer a big fat warning that somebody enabled the migrator but didn't supply the migration script.
I think the real issue here, is that liquibase can be enabled from the 'src/main/resources' AppConstants instance. It should only check in it's own context (just like the migration script.

Comment (alisihab) [reply core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowLiquibaseScript.java:82]: It is not necessary to set a property to use this tool. Having a script in the configuration classpath is sufficient.

File: core/src/main/java/nl/nn/adapterframework/jdbc/migration/DatabaseMigratorBase.java [hunk 2]
```diff
@@ -135,4 +135,18 @@ public final ApplicationContext getApplicationContext() {
...
+	public boolean hasLiquibaseScript(Configuration config) {
+		AppConstants appConstants = AppConstants.getInstance(config.getClassLoader());
+		String changeLogFile = appConstants.getString("liquibase.changeLogFile", "DatabaseChangelog.xml");
+		LiquibaseResourceAccessor resourceAccessor = new LiquibaseResourceAccessor(config.getClassLoader());
+		if(resourceAccessor.getResource(changeLogFile) == null) {
+			log.debug("No liquibase script ["+changeLogFile+"] found in the classpath of configuration ["+config.getName()+"]");
+			return false;
+		}
+		return true;
+	}
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/jdbc/migration/DatabaseMigratorBase.java:151]: Can you then please override `isEnabled` in LiquibaseMigrator and call the method `getChangeLogFile`? The method returns a FNFE, I think the easiest is to catch the exception and return false. That way the isEnabled works uniformly, and there is no duplicate code.

**Review by nielsm5 — APPROVED** [review]

**Review by gvanbrakel — APPROVED** [review]
