### PR TITLE
Fix #1743 display connectionFactoryNames in jms screens

### LINKED ISSUE #1743: JMS screens show database JMS realms
**Describe the issue**
The console has 2 screens regarding JMS (Send Message and Browse Queue), that contain a dropdown to select the JMS realm to use. This dropdown includes the JMS realms used for database connections, while the JDBC-screens properly filter out the non-JMS realms.

**Reporter**
Ricardo

**To Reproduce**
1. Go to https://ibis4example.ibissource.org/iaf/gui/#!/jms/send-message or https://ibis4example.ibissource.org/iaf/gui/#!/jms/browse-queue
2. Click on the JMS realm dropdown
3. See the "jdbc" realm which is not really a JMS realm to use on these screens

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7-SNAPSHOT: Ibis4Example
Running on vlapp05.interpar.nl using Apache Tomcat/7.0.90
Java Version: OpenJDK Runtime Environment (1.8.0_242-b08)
Heap size: 566M, total JVM memory: 1069M
Free disk space: 2GB, total disk space: 17GB
Up since: 2021-04-23 15:17:47 (5d)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]: N/A
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]: N/A

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

### PR DESCRIPTION
**Pull request by alisihab**

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/jms/JmsRealmFactory.java [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
-   Copyright 2013, 2020 Nationale-Nederlanden
+   Copyright 2013-2020 Nationale-Nederlanden, 2021 WeAreFrank!
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/jms/JmsRealmFactory.java:2]: `2013-2020` is not the same as `2013, 2020`.
The dash suggests that there are a 'lot' of changes in the whole period, whereas the comma suggests that there are some in 2013 and some in 2020

File: core/src/main/java/nl/nn/adapterframework/webcontrol/api/BrowseQueue.java [hunk 2]
```diff
@@ -55,7 +55,7 @@
 	public Response getBrowseQueue() throws ApiException {
 		Map<String, Object> returnMap = new HashMap<String, Object>();
 
-		List<String> jmsRealms=JmsRealmFactory.getInstance().getRegisteredRealmNamesAsList();
+		List<String> jmsRealms=JmsRealmFactory.getInstance().getConnectionFactoryNames();
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/webcontrol/api/BrowseQueue.java:58]: You cannot just use a connectionFactoryName as a realm name.
Preferably you update the GUI, so that it is clear that you select a connectionFactory,
and also update the code that uses it

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

File: core/src/main/java/nl/nn/adapterframework/webcontrol/api/BrowseQueue.java (hunk 2 above)
Comment (alisihab) [reply core/src/main/java/nl/nn/adapterframework/webcontrol/api/BrowseQueue.java:58]: Of course :)

File: core/src/main/java/nl/nn/adapterframework/webcontrol/api/BrowseQueue.java [hunk 3]
```diff
@@ -92,21 +93,29 @@ public Response putBrowseQueue(LinkedHashMap<String, Object> json) throws ApiExc
...
 			throw new ApiException("No type provided");
 
 		try {
-			JmsBrowser<javax.jms.Message> jmsBrowser = new JmsBrowser<>();
+			JmsBrowser<javax.jms.Message> jmsBrowser = getIbisContext().createBeanAutowireByName(JmsBrowser.class);
 			jmsBrowser.setName("BrowseQueueAction");
+			String jmsRealm = JmsRealmFactory.getInstance().findJmsRealm(connectionFactory);
+			if(jmsRealm == null) {
+				throw new ApiException("connection factory ["+connectionFactory+"] does not have a realm");
+			}
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/webcontrol/api/BrowseQueue.java:114]: You should not convert the connectionFactory back to a realm and use `setJmsRealm()`, but use `setConnectionFactory()` instead.

File: core/src/main/java/nl/nn/adapterframework/jms/JmsRealmFactory.java [hunk 4]
```diff
@@ -77,6 +77,26 @@ public JmsRealm getJmsRealm(String jmsRealmName) {
...
+		for (JmsRealm jmsRealm: jmsRealms.values()) {
+			String connectionFactory = jmsRealm.retrieveConnectionFactoryName();
+			if(StringUtils.isNotEmpty(connectionFactory)) {
+				list.add(connectionFactory);
+			}
+		}
+		return list;
+	}
+
+	public String findJmsRealm(String connectionFactory) {
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/jms/JmsRealmFactory.java:91]: This method should not be necessary

File: core/src/main/java/nl/nn/adapterframework/webcontrol/api/SendJmsMessage.java [hunk 5]
```diff
@@ -64,14 +65,20 @@ public Response putJmsMessage(MultipartBody inputDataMap) throws ApiException {
...
 		String replyTo = resolveTypeFromMap(inputDataMap, "replyTo", String.class, "");
 		boolean persistent = resolveTypeFromMap(inputDataMap, "persistent", boolean.class, false);
 		boolean synchronous = resolveTypeFromMap(inputDataMap, "synchronous", boolean.class, false);
+		boolean lookupDestination = resolveTypeFromMap(inputDataMap, "lookupDestination", boolean.class, false);
 
-		JmsSender qms = jmsBuilder(jmsRealm, destinationName, persistent, destinationType, replyTo, synchronous);
+		String jmsRealm = JmsRealmFactory.getInstance().findJmsRealm(connectionFactory);
+		if(jmsRealm == null) {
+			throw new ApiException("connection factory ["+connectionFactory+"] does not have a realm");
+		}
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/webcontrol/api/SendJmsMessage.java:79]: You should not convert the connectionFactory back to a realm and use setJmsRealm(), but used connectionFactory directly

File: core/src/main/java/nl/nn/adapterframework/webcontrol/api/BrowseQueue.java [hunk 6]
```diff
@@ -54,10 +54,11 @@
...
 	public Response getBrowseQueue() throws ApiException {
 		Map<String, Object> returnMap = new HashMap<String, Object>();
+		JmsBrowser<javax.jms.Message> jmsBrowser = getIbisContext().createBeanAutowireByName(JmsBrowser.class);
 
-		List<String> jmsRealms=JmsRealmFactory.getInstance().getRegisteredRealmNamesAsList();
-		if (jmsRealms.size()==0) jmsRealms.add("no realms defined");
-		returnMap.put("jmsRealms", jmsRealms);
+		List<String> connectionFactories=jmsBrowser.getConnectionFactoryFactory().getConnectionFactoryNames();
+		if (connectionFactories.size()==0) connectionFactories.add("no connection factories found");
+		returnMap.put("connectionFactories", connectionFactories);
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/webcontrol/api/BrowseQueue.java:61]: It think it would be the best to extending this list of connectionFactories with that found in the jmsRealms (avoiding duplicates). That allows to use connectionFactories defined in a jmsRealm, but not yet in a real configuration element.

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

File: core/src/main/java/nl/nn/adapterframework/webcontrol/api/BrowseQueue.java [hunk 7]
```diff
@@ -54,10 +56,14 @@
 	@Produces(MediaType.APPLICATION_JSON)
 	public Response getBrowseQueue() throws ApiException {
 		Map<String, Object> returnMap = new HashMap<String, Object>();
-
-		List<String> jmsRealms=JmsRealmFactory.getInstance().getRegisteredRealmNamesAsList();
-		if (jmsRealms.size()==0) jmsRealms.add("no realms defined");
-		returnMap.put("jmsRealms", jmsRealms);
+		JmsBrowser<javax.jms.Message> jmsBrowser = getIbisContext().createBeanAutowireByName(JmsBrowser.class);
+		Set<String> connectionFactories = new HashSet<String>();
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/webcontrol/api/BrowseQueue.java:60]: Could you use a LinkedHashSet instead of a plain HashSet? That keeps the order to the order of insertion, and therefor the ones used in the configuration on top of those 'only' in jsmRealms

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

File: core/src/main/java/nl/nn/adapterframework/webcontrol/api/BrowseQueue.java [hunk 8]
```diff
@@ -54,10 +56,14 @@
...
-		if (jmsRealms.size()==0) jmsRealms.add("no realms defined");
-		returnMap.put("jmsRealms", jmsRealms);
+		JmsBrowser<javax.jms.Message> jmsBrowser = getIbisContext().createBeanAutowireByName(JmsBrowser.class);
+		Set<String> connectionFactories = new LinkedHashSet<String>();
+		// connection factories used in configured jmsSenders etc.
+		connectionFactories.addAll(jmsBrowser.getConnectionFactoryFactory().getConnectionFactoryNames());
+		// configured jms realm
+		connectionFactories.addAll(JmsRealmFactory.getInstance().getConnectionFactoryNames());
+		if (connectionFactories.size()==0) connectionFactories.add("no connection factories found");
+		returnMap.put("connectionFactories", connectionFactories);
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/webcontrol/api/BrowseQueue.java:66]: I don't see you use the jmsBrowser anywhere else other then to fetch the `JndiConnectionFactoryFactory`
It might be simpler to autowire the required class directly instead.
`getIbisContext().getBean("connectionFactoryFactory", JndiConnectionFactoryFactory.class)`

**Review by nielsm5 — APPROVED** [review]

**Review by gvanbrakel — APPROVED** [review]
