### PR TITLE
Fix disable template in stubbing xsl

### LINKED ISSUE #2849: EsbJmsListener throws exception if queueConnectionFactoryName is not set in Frank config
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

An EsbJmsListener throws an exception if its queueConnectionFactoryName attribute is not set in a Frank config. This behavior only applies to recent versions. The first version with this behavior is 7.8-20220224.160034. If you start the Frank!Runner with an earlier version of the F!F, a configuration with a EsbJmsListener without queueConnectionFactoryName does not result in an error in the adapter status page.

I found this issue when working with the performance test: https://github.com/ibissource/ibis4pt. I see two possible solutions: either we edit the performance test to provide a queueConnectionFactoryName, or we update the F!F again to accept configs without a queueConnectionFactoryName.

**Reporter**
Martijn Dirkse

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

### PR DESCRIPTION
**Pull request by alisihab**
Closes #2849

### CODE REVIEW

**Review by gvanbrakel — APPROVED** [review]

**Review by nielsm5 — CHANGES_REQUESTED** [review]
Is it possible to also test the commented section  `<!--` ... `-->` ?

**Review by nielsm5 — APPROVED** [review]

File: core/src/test/java/nl/nn/adapterframework/configuration/digester/ConfigurationDigesterTest.java [hunk 1]
```diff
@@ -131,6 +131,30 @@ public void stub4testtoolTest() throws Exception {
...
+		
+		ConfigurationDigester digester = new ConfigurationDigester();
+		ContentHandler filter = digester.getStub4TesttoolContentHandler(xmlWriter, properties);
+		
+		XmlUtils.parseXml(originalConfiguration, filter);
+		
+		String actual = new String(target.toString());
+
+		String expectedConfiguration = TestFileUtils.getTestFile(baseDirectory + "/expected.xml");
+		MatchUtils.assertXmlEquals(null, expectedConfiguration, actual, false, true);
```
Comment (gvanbrakel) [inline core/src/test/java/nl/nn/adapterframework/configuration/digester/ConfigurationDigesterTest.java:156]: This test does not test for the current problem situation: that the produced stream looks like XML with comments, but the events from which it is produced do not have the stubbed commented out

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

File: core/src/test/java/nl/nn/adapterframework/configuration/digester/ConfigurationDigesterTest.java [hunk 2]
```diff
@@ -131,6 +133,39 @@ public void stub4testtoolTest() throws Exception {
...
+		StringWriter target = new StringWriter();
+
+		XmlWriter xmlWriter = new XmlWriter(target) {
+			@Override
+			public void comment(char[] ch, int start, int length) throws SAXException {
+				if(!new String(ch).startsWith("<receiver name='receiver' transactionAttribute='Required' transactionTimeout=")) {
+					fail("Digester should have commented out the receiver that has EsbJmsListener");
+				}
+				super.comment(ch, start, length);
+			}
```
Comment (gvanbrakel) [inline core/src/test/java/nl/nn/adapterframework/configuration/digester/ConfigurationDigesterTest.java:150]: You should also override startElement() and check that there is not a listener element with className EsbJmsListener

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

**Review by gvanbrakel — APPROVED** [review]
