### PR TITLE
Fix #1959 get session key as string

### LINKED ISSUE #1959: XsltSender cannot find [String: TLE/OUTPUTSTUK/RP020.xsl] in scope [nl.nn.adapterframework.senders.XsltSender@22bdb88a]
**Problem**
We are getting the following error.
nl.nn.adapterframework.core.PipeRunException: Pipe [SendToFTConfig_TLE] msgId [5014904] caught exception: IbisLocalSender [SendToFTConfig_TLE] exception calling JavaListener [FTSendersListener_TLE]: Pipe [ROSY_TLE] msgId [5014904] caught exception: IbisLocalSender [ROSY_TLE] exception calling JavaListener [ROSY_TLE]: Pipe [Mapping_TLE_Outputstuk] msgId [5014904] Exception on transforming input: XsltSender [Mapping_TLE_Outputstuk] Exception on transforming input: XsltSender [Mapping_TLE_Outputstuk] Exception on creating transformerHandler chain: XsltSender [Mapping_TLE_Outputstuk] cannot find [String: TLE/OUTPUTSTUK/RP020.xsl] in scope [nl.nn.adapterframework.senders.XsltSender@22bdb88a]

Framework information : 
**FF! 7.7-20210624.162049: ibis4oma ---
Running on LPZWNL000024275 using Apache Tomcat/9.0.39
Java Version: OpenJDK Runtime Environment (1.8.0_252-b09)
Heap size: 263M, total JVM memory: 455M
Free disk space: 99GB, total disk space: 237GB
Up since: 2021-06-25 15:44:41 (2d)**

**Reporter**
Mouli Banerjee

Ali sent me a custom java file <HttpSender.java> **only for local test**. This issue is solved with this custom file.

Waiting for an upgraded framework version to be applied on OTAP.

### PR DESCRIPTION
**Pull request by alisihab**
Closes #1959

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/senders/XsltSender.java [hunk 1]
```diff
@@ -186,18 +186,17 @@ protected ContentHandler createHandler(Message input, PipeLineSession session, M
 
 			TransformerPool poolToUse = transformerPool;
 			if(StringUtils.isNotEmpty(styleSheetNameSessionKey)) {
-				if (session.get(styleSheetNameSessionKey) != null) {
-					String styleSheetNameToUse = session.get(styleSheetNameSessionKey).toString();
-				
+				String styleSheetNameToUse = session.getMessage(styleSheetNameSessionKey).asString();
+				if (styleSheetNameToUse != null) {
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/senders/XsltSender.java:190]: I think it's safer to do a nullcheck before doing asString.
You can do
```
Message styleSheetNameToUse = session.getMessage(styleSheetNameSessionKey);
if (!Message.isEmpty(styleSheetNameToUse )) { ... }
```

File: RELEASES.md [hunk 2]
```diff
@@ -19,6 +19,7 @@ Upcoming
 - SoapErrorMessage is renamed to SoapErrorMessageFormatter.
 - FixedErrorMessage is renamed to FixedErrorMessageFormatter.
 - ManageDatabase adapter has been disabled by default on ACC and PRD environments
+- JsonPipe produces json without root element
```
Comment (gvanbrakel) [inline RELEASES.md:22]: Please add: the previous  behaviour can be obtained by setting `version="1"`

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

**Review by gvanbrakel — APPROVED** [review]
