### PR TITLE
Fix #1751 Add option to use ServerFileName as the filename to FxfWrapperPipe

### LINKED ISSUE #1751: FxFWrapper unwrap generates wrong filename
**Describe the issue**
When using the FxFWrapper to unwrap messages, the outputted filename is based on the ClientFilename element, but there are multiple problems with this:
- It contains the filename as known on the source system, which might not match the filename as delivered in the ServerFilename
- The path can contain \ as path separator, which results in the complete contents of ClientFilename being used as filename instead of only the part after the last /

**Reporter**
Ricardo

**To Reproduce**
1. Create an adapter with an FxfWrapper with direction unwrap
2. Put in the example message listed below
3. Output is '/opt/data/WAS/wasap01/fxf-work/NNX00000/in/E:\Source\FilenameXYZ' instead of expected '/opt/data/WAS/wasap01/fxf-work/NNX00000/in/Filename'

**Screenshots**
N/A

**Configuration**
```
<inputWrapper className="nl.nn.adapterframework.extensions.fxf.FxfWrapperPipe" direction="unwrap" storeResultInSessionKey="inputAdress"/>
```

**Input**
```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
<SOAP-ENV:Body>
<ns0:OnCompletedTransferNotify_Action xmlns:ns0="http://nn.nl/XSD/Infrastructure/Transfer/FileTransfer/1/OnCompletedTransferNotify/1">
<ns0:TransferFlowId>NNT00000</ns0:TransferFlowId>
<ns0:UserData>NNT00000-ibis4x</ns0:UserData>
<ns0:ClientFilename>E:\Source\FilenameXYZ</ns0:ClientFilename>
<ns0:ServerFilename>/opt/data/FXF/IBIS4X/NNX00000/in/Filename</ns0:ServerFilename>
<ns0:LocalTransactionID>I000000000</ns0:LocalTransactionID>
</ns0:OnCompletedTransferNotify_Action>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

**Environment**
```
FF! 7.6-20201123.110830: 
Running on  using IBM WebSphere Application Server/9.0.5.3
Java Version: Java(TM) SE Runtime Environment (8.0.6.6 - pxa6480sr6fp6ifix-20200317_01(SR6 FP6+IJ22800+IJ23014+IJ23018))
Heap size: 754M, total JVM memory: 2048M
Free disk space: 2GB, total disk space: 2GB
Up since: 2021-04-23 12:09:36 (6d)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]: Oracle
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]: Chrome

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

### PR DESCRIPTION
**Pull request by alisihab**
Closes #1751

### CODE REVIEW

File: core/src/test/java/nl/nn/adapterframework/extensions/fxf/FxfWrapperPipeTest.java [hunk 1]
```diff
@@ -0,0 +1,113 @@
...
+	@Test
+	public void testBasicUnwrap() throws Exception {
+		pipe.setDirection("unwrap");
+		pipe.configure();
+		PipeRunResult pipeRunResult = doPipe(new Message("<SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\">\n" + 
+				"<SOAP-ENV:Body>\n" + 
+				"<ns0:OnCompletedTransferNotify_Action xmlns:ns0=\"http://nn.nl/XSD/Infrastructure/Transfer/FileTransfer/1/OnCompletedTransferNotify/1\">\n" + 
+				"<ns0:TransferFlowId>FlowId</ns0:TransferFlowId>\n" + 
+				"<ns0:UserData>FlowId-Instance</ns0:UserData>\n" + 
+				"<ns0:ClientFilename>/filename.xml.zip</ns0:ClientFilename>\n" +
```
Comment (gvanbrakel) [inline core/src/test/java/nl/nn/adapterframework/extensions/fxf/FxfWrapperPipeTest.java:37]: Could you also test without an initial slash?

File: core/src/main/java/nl/nn/adapterframework/extensions/fxf/FxfWrapperPipe.java [hunk 2]
```diff
@@ -128,7 +130,8 @@ public void configure() throws ConfigurationException {
 				throw new ConfigurationException("fxf.dir [" + fxfDir + "] doesn't exist or is not a directory");
 			}
 			transferFlowIdTp = XmlUtils.getXPathTransformerPool(null, "/OnCompletedTransferNotify_Action/TransferFlowId", "text", false, getParameterList());
-			clientFilenameTp = XmlUtils.getXPathTransformerPool(null, "/OnCompletedTransferNotify_Action/ClientFilename", "text", false, getParameterList());
+			String xpathFilename = isUseServerFilename() ? "/OnCompletedTransferNotify_Action/ServerFilename" : "/OnCompletedTransferNotify_Action/ClientFilename";
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/extensions/fxf/FxfWrapperPipe.java:133]: Could you make constants for the fixed string values?

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

**Review by gvanbrakel — APPROVED** [review]

**Review by nielsm5 — APPROVED** [review]
