### PR TITLE
Small fixes in gui

### LINKED ISSUE #2692: Timestamp filter in errorstore does not work correctly
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The timestamp filter option does not work correctly
- if you put in a date only it does not select all records for this date 
- if you put in a complete timestamp it does not filter

in the old blue 

**Reporter**
JJansenvr

**To Reproduce**
1. Go to an adapter with a error or message store 
2. Click on Display Filters
3. Scroll down to fill out the timestamp filter field
4. See no (or no correct) filtering in the list

**Screenshots**

**Configuration**
```
na
```

**Input**
```
na
```

**Environment**
```


FF! 7.6: ibis4-----
Running on srtapp0000 using IBM WebSphere Application Server/9.0.5.7
Java Version: Java(TM) SE Runtime Environment (8.0.6.26 - pxa6480sr6fp26-20210216_01(SR6 FP26))
Heap size: 839M, total JVM memory: 1240M
Free disk space: 466MB, total disk space: 2GB
Up since: 2022-01-13 10:14:49 (14d)

```

**Additional Environment**
 - Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production Version 19.13.0.0.0] driver [Oracle JDBC driver] driver version [18.3.0.0.0]

 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**

### PR DESCRIPTION
**Pull request by alisihab**
Closes #2692

### CODE REVIEW

**Review by nielsm5 — APPROVED** [review]

File: core/src/main/java/nl/nn/adapterframework/util/MessageBrowsingFilter.java [hunk 1]
```diff
@@ -99,15 +99,15 @@ public boolean matchAny(IMessageBrowsingIteratorItem iterItem) throws ListenerEx
 		}
 		if(startDate != null && endDate == null) {
 			count++;
-			matches += iterItem.getInsertDate().after(startDate) ? 1 : 0;
+			matches += (iterItem.getInsertDate().after(startDate) || iterItem.getInsertDate().equals(startDate)) ? 1 : 0;
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/util/MessageBrowsingFilter.java:102]: it would be more efficient to program this after-or-equal as not-before

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

**Review by gvanbrakel — APPROVED** [review]
