### PR TITLE
Show restlistener method in webservices view

### LINKED ISSUE #2575: Add methods to Rest Services GUI
**❗ please do not add sensitive infomation in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
In the Webservices tab of the GUI, Rest services, provided by RestListeners, do not show their method, like is done for ApiListeners.
It would be an improvement to show these in the same way as for ApiListeners

**Reporter**
Gerrit

**To Reproduce**
1. Go to Webservices in GUI

**Environment**
```
FF! 7.7-SNAPSHOT: Ibis4Example
Running on vlapp05.interpar.nl using Apache Tomcat/7.0.90
Java Version: OpenJDK Runtime Environment (1.8.0_242-b08)
Heap size: 160M, total JVM memory: 1074M
Free disk space: 9GB, total disk space: 17GB
Up since: 2021-12-22 12:27:07 (3d)
```

### PR DESCRIPTION
**Pull request by alisihab**
Closes #2575

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/webcontrol/api/Webservices.java [hunk 1]
```diff
@@ -86,6 +86,7 @@ public Response getWebServices() throws ApiException {
 					if (rl.isView()) {
 						Map<String, Object> service = new HashMap<String, Object>(2);
 						service.put("name", adapter.getName() + " "+  receiver.getName());
+						service.put("method", rl.getMethod());
 						service.put("uriPattern", rl.getUriPattern());
 						webServices.add(service);
 					}
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/webcontrol/api/Webservices.java:92]: Does this only show the 'vieawable' restlisteners?

Comment (alisihab) [reply core/src/main/java/nl/nn/adapterframework/webcontrol/api/Webservices.java:92]: yes

Comment (nielsm5) [reply core/src/main/java/nl/nn/adapterframework/webcontrol/api/Webservices.java:92]: This doesn't add all restlisteners to the GUI, only the method (which is always `GET` for listeners with isView).
I suggest removing the isView or adding it as attribute.

**Review by nielsm5 — CHANGES_REQUESTED** [review]

**Review by nielsm5 — APPROVED** [review]

**Review by gvanbrakel — APPROVED** [review]
