### PR TITLE
Show liquibase exceptions in configuration warnings

### LINKED ISSUE #1132: Liquibase validation exception gives no error
**Describe the bug**
If the Liquibase validation step fails with a ValidationFailedException because of changed checksums Liquibase is not executed. This exception is only logged as INFO and is not visible in the GUI, making it hard to track if something is wrong with the database, that this might be the issue. This can already happen with the Framework-provided IAF_DatabaseChangelog.xml, as IAF_Util:1 has had a change without updating the valid checksums. 

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
1. Start an ibis on 7.5-RC3 with jdbc.migrator.active=true
2. Upgrade to latest snapshot and start again
3. Browse tables and check IBISSCHEDULES table
4. This fails because IBISSCHEDULES is not created
5. Check logging, see warning for changeset IAF_Util:1

**Expected behavior**
A warning to be shown in the interface that Liquibase has had an exception and has not been executed.

**Screenshots**

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Tomcat/WebSphere
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6-20200909.154756

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

### PR DESCRIPTION
**Pull request by alisihab**
Fixes #1132

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/configuration/IbisContext.java [hunk 1]
```diff
@@ -351,6 +351,7 @@ private void digestClassLoaderConfiguration(ClassLoader classLoader,
 						databaseMigrator.close();
 					}
 					catch (Exception e) {
+						ConfigurationWarnings.add(LOG, e.getMessage());
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/configuration/IbisContext.java:354]: I don't think it is a good idea to log this message in the ConfigurationWarnings as well as in the MessageKeeper.

Comment (alisihab) [reply core/src/main/java/nl/nn/adapterframework/configuration/IbisContext.java:354]: I do agree

**Comment by nielsm5** [comment]
I don't think this is a good idea; configuration independent warnings are persistent. Fixing the issue will not remove the error, until a JVM restart. 
The issue states the message is logged as INFO and not as ERROR. Why is that?
Also there does not appear to be a clear message in the interface, only when you click on the configuration. Perhaps configuration errors and warnings also need to be added to the `*ALL*` MessageKeeper?

**Comment by nielsm5** [comment]
Global status page image
Why are info messages printed in the global MessageKeeper as well as the configuration specific MessageKeeper?

Config status page 
image

File: core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationDigester.java [hunk 2]
```diff
@@ -100,15 +100,15 @@
 	private class XmlErrorHandler implements ErrorHandler  {
 		@Override
 		public void warning(SAXParseException exception) throws SAXParseException {
-			ConfigurationWarnings.add(log, "Warning when validating against schema ["+CONFIGURATION_VALIDATION_SCHEMA+"] at line,column ["+exception.getLineNumber()+","+exception.getColumnNumber()+"]: " + exception.getMessage());
+			ConfigurationWarnings.addGlobalWarning(log, "Warning when validating against schema ["+CONFIGURATION_VALIDATION_SCHEMA+"] at line,column ["+exception.getLineNumber()+","+exception.getColumnNumber()+"]: " + exception.getMessage());
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationDigester.java:103]: These warnings are very configuration specific. If you pass the Configuration that is parsed in the constructor of XmlErrorHandler, than you can make these warnings configuration specific

File: core/src/main/java/nl/nn/adapterframework/jdbc/migration/LiquibaseImpl.java [hunk 3]
```diff
@@ -37,7 +38,7 @@
  * @since	7.0-B4
  *
  */
-public class LiquibaseImpl {
+public class LiquibaseImpl implements INamedObject{
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/jdbc/migration/LiquibaseImpl.java:41]: LiquibaseImpl is not really a named object, so this is a tricky/hacky way to pass the name.
I suggest you pass the Configuration as an argument to databaseMigrator.configure() in IbisContext line 349, and use that as the named object

File: core/src/main/java/nl/nn/adapterframework/unmanaged/DefaultIbisManager.java [hunk 4]
```diff
@@ -119,7 +119,7 @@ private void updateFlowDiagram(Configuration configuration) {
 			try {
 				flowDiagramManager.generate(configuration);
 			} catch (IOException e) {
-				ConfigurationWarnings.add(log, "Error generating flow diagram for configuration ["+configuration.getName()+"]", e);
+				ConfigurationWarnings.addGlobalWarning(log, "Error generating flow diagram for configuration ["+configuration.getName()+"]", e);
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/unmanaged/DefaultIbisManager.java:122]: This can be a configuration warning

File: core/src/main/java/nl/nn/adapterframework/validation/XercesXmlValidator.java [hunk 5]
```diff
@@ -132,7 +132,7 @@
 				cache.open();
 			} catch (ConfigurationException e) {
 				cache = null;
-				ConfigurationWarnings.add(log, "Could not configure EhCache for XercesXmlValidator (xmlValidator.maxInitialised will be ignored)", e);
+				ConfigurationWarnings.addGlobalWarning(log, "Could not configure EhCache for XercesXmlValidator (xmlValidator.maxInitialised will be ignored)", e);
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/validation/XercesXmlValidator.java:135]: This can be a configuration warning

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

File: core/src/main/java/nl/nn/adapterframework/jdbc/migration/Migrator.java [hunk 6]
```diff
@@ -41,19 +42,16 @@ public Migrator() {
...
 
-	public void configure(String configurationName, ClassLoader classLoader) throws ConfigurationException {
-		configure(configurationName, classLoader, null);
-	}
-
-	public synchronized void configure(String configurationName, ClassLoader classLoader, String changeLogFile) throws ConfigurationException {
-		setName("JdbcMigrator for configuration["+configurationName+"]");
+	public synchronized void configure(Configuration configuration, ClassLoader classLoader, String changeLogFile) throws ConfigurationException {
+		setName("JdbcMigrator for configuration["+ configuration.getName() +"]");
+		super.configure();
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/jdbc/migration/Migrator.java:54]: You don't need to specify the `ClassLoader` as you can retrieve this from the `Configuration`.

File: core/src/main/java/nl/nn/adapterframework/jdbc/DirectQuerySender.java [hunk 7]
```diff
@@ -50,7 +50,7 @@ public void configure() throws ConfigurationException {
 	public void configure(boolean trust) throws ConfigurationException {
 		super.configure();
 		if (!trust) {
-			ConfigurationWarnings.add(log, "The class ["+ClassUtils.nameOf(this)+"] is used one or more times. This may cause potential SQL injections!");
+			ConfigurationWarnings.addGlobalWarning(log, "The class ["+ClassUtils.nameOf(this)+"] is used one or more times. This may cause potential SQL injections!");
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/jdbc/DirectQuerySender.java:53]: This can be a configuration warning

File: core/src/main/java/nl/nn/adapterframework/configuration/IbisContext.java [hunk 8]
```diff
@@ -343,15 +343,15 @@ private void digestClassLoaderConfiguration(ClassLoader classLoader,
 				ConfigurationWarnings.getInstance().setActiveConfiguration(configuration);
 
 				if(AppConstants.getInstance(classLoader).getBoolean("jdbc.migrator.active", false)) {
+					Migrator databaseMigrator = getBean("jdbcMigrator", Migrator.class);
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/configuration/IbisContext.java:346]: Might be best to leave this in the try/catch, as otherwise it can prevent the configuration from starting up.

**Review by nielsm5 — CHANGES_REQUESTED** [review]

File: core/src/main/java/nl/nn/adapterframework/jdbc/migration/Migrator.java [hunk 9]
```diff
@@ -41,30 +43,27 @@ public Migrator() {
...
 			changeLogFile = appConstants.getString("liquibase.changeLogFile", "DatabaseChangelog.xml");
 
-		LiquibaseClassLoaderWrapper cl = new LiquibaseClassLoaderWrapper(classLoader);
+		LiquibaseClassLoaderWrapper cl = new LiquibaseClassLoaderWrapper(configuration.getClassLoader());
 		if(cl.getResource(changeLogFile) == null) {
 			String msg = "unable to find database changelog file ["+changeLogFile+"]";
-			if(configurationName != null)
-				msg += " classLoader ["+ClassUtils.nameOf(classLoader)+"]";
+			if(configuration.getName() != null)
+				msg += " classLoader ["+ClassUtils.nameOf(configuration.getClassLoader())+"]";
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/jdbc/migration/Migrator.java:66]: The null check is not necessary here anymore

File: core/src/main/java/nl/nn/adapterframework/unmanaged/DefaultIbisManager.java (hunk 4 above)
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/unmanaged/DefaultIbisManager.java:122]: This can be a configuration warning

File: core/src/main/java/nl/nn/adapterframework/validation/XercesXmlValidator.java (hunk 5 above)
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/validation/XercesXmlValidator.java:135]: This can be a configuration warning

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

File: core/src/main/java/nl/nn/adapterframework/validation/XercesXmlValidator.java (hunk 5 above)
Comment (alisihab) [reply core/src/main/java/nl/nn/adapterframework/validation/XercesXmlValidator.java:135]: it is in a static block where we don't have the configuration info

**Review by gvanbrakel — APPROVED** [review]

**Review by nielsm5 — APPROVED** [review]
