### PR TITLE
Fix incorrect message id in message store

### LINKED ISSUE #2964: Error when browsing Exchange message
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When browsing messages in folders of an ExchangeMailListener, an error message appears: `Cannot convert filename [<span class=\"ellipsis\" title=\"AAMkAGNmZTczMWUwLWQ1MDEtNDA3Ny1hNjU4LTlmYTQzNjE0NjJmYgBGAAAAAAALFKqetECyQKQyuRBrRSzgBwDx14SZku4LS5ibCBco+nmXAAMWB/6iAADx14SZku4LS5ibCBco+nmXAAMdRHaAAAA=\">AAMkAGNmZTczMWU &#8230; nmXAAMdRHaAAAA=</span>] into an ItemId: (ServiceResponseException) Id is malformed.`

**Reporter**
Gerrit

**To Reproduce**
1. In iaf-test, enable the ExchangeMailListener, by setting properties:
    ```
        exchangemail.active=true
        exchangemail.mailAddress=<your email address>
        exchangemail.username=<your email address or username>
        exchangemail.password=<your password>
    ```
2. Prepare folders in your Outlook, according to DeploymentSpecifics.properties:
    ```
        exchangemail.baseFolder=IafTest
        exchangemail.inputFolder=InputExchange
        exchangemail.inProcessFolder=InProcess
        exchangemail.processedFolder=Done
        exchangemail.errorFolder=Error
   ```
3. Start iaf-test
4. Move a message to InputExchange to get it picked up
5. See that it is processed
6. Browse the folder where it is moved to
7. See the error:
image

**Configuration**
```
		<receiver name="ExchangeMail" active="${exchangemail.active}">
			<listener
				className="nl.nn.adapterframework.receivers.ExchangeMailListener"
				url="${exchangemail.url}"
				mailAddress="${exchangemail.mailAddress}"
				authAlias="${exchangemail.authAlias}"
				username="${exchangemail.username}"
				password="${exchangemail.password}"
				baseFolder="${exchangemail.baseFolder}"
				inputFolder="${exchangemail.inputFolder}"
				inProcessFolder="${exchangemail.inProcessFolder}"
				processedFolder="${exchangemail.processedFolder}"
				errorFolder="${exchangemail.errorFolder}"
				createFolders="true"
				disableMessageBrowsers="${exchangemail.disableMessageBrowsers}"
				messageType="contents"
			/>
		</receiver>

```

**Input**
```
any input
```

**Environment**
```
FF! 7.8-SNAPSHOT: Ibis4Test
Running on LPZWNL000040524 using Apache Tomcat/9.0.60
Java Version: OpenJDK Runtime Environment (1.8.0_312-b07)
Heap size: 378M, total JVM memory: 428M
Free disk space: 110GB, total disk space: 476GB
Up since: 2022-04-01 09:30:10 (22m)
```

### PR DESCRIPTION
**Pull request by alisihab**
Close #2964

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java [hunk 1]
```diff
@@ -140,6 +140,7 @@ private StorageItemDTO getMessageMetadata(IMessageBrowser<?> storage, String mes
 
 	public static class StorageItemDTO {
 		private @Getter String id; //MessageId
+		private @Getter String messageId; // just to display truncated data
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java:143]: Could you use descriptive names here, like 'id' and 'displayedId'

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

File: core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java (hunk 1 above)
Comment (nielsm5) [reply core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java:143]: Id and messageid is the same?!

File: webapp/src/main/webapp/iaf/gui/js/controllers.js [hunk 2]
```diff
@@ -1447,9 +1447,11 @@ angular.module('iaf.beheerconsole')
...
 				if(type === 'display'){
 					for(let i in data){
-						var columnData = data[i];
-						if(typeof columnData == 'string' && columnData.length > 30)
-							data[i] = '<span class="ellipsis" title="'+columnData+'">'+columnData.substr(0, 15)+' &#8230; '+columnData.substr(-15)+'</span>';
+						if(i !=='id'){
+							var columnData = data[i];
+							if(typeof columnData == 'string' && columnData.length > 30)
+								data[i] = '<span title="'+columnData.replace(/"/g, '&quot;')+'">'+columnData.substr(0, 15)+' &#8230; '+columnData.substr(-15)+'</span>';
+						}
```
Comment (nielsm5) [inline webapp/src/main/webapp/iaf/gui/js/controllers.js:1454]: This should work without changing/adding a new column...?

**Review by nielsm5 — CHANGES_REQUESTED** [review]

File: webapp/src/main/webapp/iaf/gui/js/controllers.js (hunk 2 above)
Comment (alisihab) [reply webapp/src/main/webapp/iaf/gui/js/controllers.js:1454]: This changes/truncates the actual populated data in the table. Clicking View button uses this new data/id (<span ...) to fetch the from backend. To prevent this I created a new field messageId that will be truncated and the actual id will stay unchanged.

File: webapp/src/main/webapp/iaf/gui/js/controllers.js [hunk 3]
```diff
@@ -1445,11 +1445,14 @@ angular.module('iaf.beheerconsole')
 		columnDefs: [ {
 			targets: 0,
 			render: function ( data, type, row ) {
-				if(type === 'display'){
-					for(let i in data){
+				if(type === 'display') {
+					data["messageId"] = data["id"];
```
Comment (nielsm5) [inline webapp/src/main/webapp/iaf/gui/js/controllers.js:1449]: i copied the data here

File: webapp/src/main/webapp/iaf/gui/js/controllers.js [hunk 4]
```diff
@@ -1445,11 +1445,14 @@ angular.module('iaf.beheerconsole')
...
+					for(let i in data) {
+						if(i == "id") continue;
 						var columnData = data[i];
-						if(typeof columnData == 'string' && columnData.length > 30)
-							data[i] = '<span class="ellipsis" title="'+columnData.replace(/"/g, '&quot;')+'">'+columnData.substr(0, 15)+' &#8230; '+columnData.substr(-15)+'</span>';
+						if(typeof columnData == 'string' && columnData.length > 30) {
+							data[i] = '<span title="'+columnData.replace(/"/g, '&quot;')+'">'+columnData.substr(0, 15)+' &#8230; '+columnData.substr(-15)+'</span>';
+						}
```
Comment (nielsm5) [inline webapp/src/main/webapp/iaf/gui/js/controllers.js:1455]: so this 'modified' data is only to display and not process

File: core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java [hunk 5]
```diff
@@ -409,8 +410,11 @@ public Response resendReceiverMessage(
 
 		// messageId is double URLEncoded, because it can contain '/' in ExchangeMailListener
 		messageId = Misc.urlDecode(messageId);
-
-		resendMessage(receiver, messageId);
+		try {
+			resendMessage(receiver, messageId);
+		} catch(ApiException e) {
+			return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity(Arrays.asList(e.getCause().getMessage())).build();
+		}
```
[the remark this answers is not in the document]
Comment (alisihab) [reply core/src/main/java/nl/nn/adapterframework/webcontrol/api/TransactionalStorage.java:417]: In controller line 1346, data will be undefined otherwise.

File: webapp/src/main/webapp/iaf/gui/js/controllers.js (hunk 4 above)
Comment (alisihab) [reply webapp/src/main/webapp/iaf/gui/js/controllers.js:1455]: Okay, I see it now. Thanks!

**Review by nielsm5 — APPROVED** [review]
