### PR TITLE
Fix#1142 datasource lookup with tomcat jndi prefix

### LINKED ISSUE #1142: Using non-default datasourceName results in NameNotFoundException
**Describe the bug**
I have a Frank with multiple database connections, but I can only use the jdbc.datasource.default. Using other datasources result in NameNotFoundException.
When sing Execute Query/Browse Tables:
`An error occured on executing jdbc query [null]: Could not find Datasource [jdbc/ibis4reproduction2]: (NameNotFoundException) Name [jdbc/ibis4reproduction2] is not bound in this Context. Unable to find [jdbc].`

When using the attribute datasourceName on a FixedQuerySender:
`ERROR: got error starting PipeLine: Pipe [Query] could not start: Could not find Datasource [jdbc/ibis4reproduction2]: (NameNotFoundException) Name [jdbc/ibis4reproduction2] is not bound in this Context. Unable to find [jdbc].`

For senders, a workaround is using the attribute jmsRealm instead of datasourceName.

Strangely enough, Liquibase runs fine with different datasource-names configured.

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Console
 - Frank Framework

**To Reproduce**
1. Have a Frank/Ibis with multiple database connections
2. Click on 'Browse Tables'
3. Select the non-default datasource, fill in the rest of the fields and press Send

**Expected behavior**
No exception, configurations being loaded correctly.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Tomcat
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6-20201009.115713

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by alisihab**
Fixes #1142

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/jms/JNDIBase.java [hunk 1]
```diff
@@ -60,6 +65,13 @@
 
 	private Context context = null;
 
+	@Override
+	public void configure() throws ConfigurationException {
+		if(StringUtils.isEmpty(jndiContextPrefix)) {
+			jndiContextPrefix = AppConstants.getInstance(configurationClassLoader).getString("jndiContextPrefix","");
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/jms/JNDIBase.java:71]: I don't understand why this is necessary

**Review by gvanbrakel — APPROVED** [review]

File: core/src/main/java/nl/nn/adapterframework/jms/JNDIBase.java (hunk 1 above)
Comment (nielsm5) [reply core/src/main/java/nl/nn/adapterframework/jms/JNDIBase.java:71]: When a database is not initialized through Spring you manually have to set the jndiContextPrefix.. Maybe good to add as comment?

**Review by nielsm5 — APPROVED** [review]

**Review by nielsm5 — APPROVED** [review]
