### PR TITLE
Fix #1285 make FixedResultPipe consume message

### LINKED ISSUE #1285: ApiListener NPE+no response to client
**Describe the bug**
When using ApiListeners, I get a lot of NPEs. Calling clients also do not get a response, while the console says all OK, only in the logging the NPEs are shown (as warnings). This does not happen for all adapters with ApiListeners, some work correctly while others that are similar do not work.

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
Unknown, issue only happens in ACC, TST has no issue.

**Expected behavior**
No NPE, client gets response

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): WebSphere 9.0
 - Browser [e.g. chrome, safari]: N/A
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6-20201123.110830

**Additional context**
[SystemOut.log](https://github.com/ibissource/iaf/files/5582764/SystemOut.log)
[ibis.log](https://github.com/ibissource/iaf/files/5582765/ibis.log)

### PR DESCRIPTION
**Pull request by gvanbrakel**

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/pipes/FixedResult.java [hunk 1]
```diff
@@ -15,285 +15,10 @@
...
-
-	@IbisDoc({"when set <code>true</code>, any parameter is used for replacements but with <code>name-of-parameter</code> and not <code>${name-of-parameter}</code>", "false"})
-	public void setReplaceFixedParams(boolean b){
-		replaceFixedParams=b;
-	}
-	public boolean isReplaceFixedParams(){
-		return replaceFixedParams;
-	}
+@Deprecated
+@ConfigurationWarning("has been renamed into FixedResultPipe")
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/pipes/FixedResult.java:21]: rename to

File: core/src/main/java/nl/nn/adapterframework/pipes/FixedResultPipe.java [hunk 2]
```diff
@@ -0,0 +1,302 @@
...
+					replaceFrom=pv.getDefinition().getName();
+				} else {
+					replaceFrom="${"+pv.getDefinition().getName()+"}";
+				}
+				result=replace(result,replaceFrom,pv.asStringValue(""));
+			}
+		}
+
+		try (Reader dummy = message.asReader()) {
+			// get the inputstream and close it, to avoid connection leaking when the message itself is not consumed
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/pipes/FixedResultPipe.java:175]: connection leaking when... explain the httpsender scenario

**Review by nielsm5 — APPROVED** [review]
