### PR TITLE
Fix initialization of transformer pool with different xslt versions in XmlSwitch pipe

### LINKED ISSUE #2204: IAF (7.5/7.6) xsltVersion issue
**Describe the issue**
We've recently upgraded the IAF version of one of our Ibises to 7.6. From then onward, we are getting the mentioned error at the mentioned pipe (switch pipe). This works fine in version 7.0-RC3

Pipe name (look at the attached TTR )-> checkFor:Updating_WGPAccount
---------------------------------------------
**ERROR->**

Pipe [checkFor:Updating_WGPAccount] msgId [ID:EMS_TST_ESB_P2P_SMALL.5F5B612A1658183485AA:6352] got exception on transformation: (XPathException) line [1]: Cannot compare xs:string to xs:integer
--------------------------------------------------

**Reporter**
Biplab Chakraborty

**Input**
Attached TTR file.
[Pipeline.SetPortalSetUpMutation.zip](https://github.com/ibissource/iaf/files/7171536/Pipeline.SetPortalSetUpMutation.zip)

### PR DESCRIPTION
**Pull request by alisihab**
Fixes #2204

### CODE REVIEW

File: core/src/test/java/nl/nn/adapterframework/pipes/XmlSwitchTest.java [hunk 1]
```diff
@@ -92,7 +93,7 @@ public void xPathFromParameterWildCardNamespaced() throws Exception {
 		inputParameter.setType("domdoc");
 		pipe.addParameter(inputParameter);
 		session.put("sessionKey", input);
-		pipe.setXsltVersion(1);
```
Comment (nielsm5) [inline core/src/test/java/nl/nn/adapterframework/pipes/XmlSwitchTest.java:95]: Why did you remove this? did the above change break this?

Comment (alisihab) [reply core/src/test/java/nl/nn/adapterframework/pipes/XmlSwitchTest.java:95]: yes

**Review by gvanbrakel — APPROVED** [review]

**Review by nielsm5 — APPROVED** [review]
