### PR TITLE
Generic way to store ConfigurationWarnings

### LINKED ISSUE #1058: ResultSetIteratingPipe gives (incorrect) warning for potential SQL injections
**Describe the bug**
When using a ResultSetIteratingPipe, the following warning is shown:
`The class [nl.nn.adapterframework.jdbc.JdbcIteratingPipeBase$MixedQuerySender] is used one or more times. Please change to [nl.nn.adapterframework.jdbc.FixedQuerySender] to avoid potential SQL injections!`

This happens because it uses a MixedQuerySender that extends the DirectQuerySender. I have set the query parameter of the ResultSetIteratingPipe, so I do not expect the warning to apply to my case and thus not to be shown.

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Console
 - Frank Framework

**To Reproduce**
1. Have a ResultSetIteratingPipe with the query parameter set
2. Load the adapter
3. See warning

**Expected behavior**
No warning, as I'm using a fixed query.

**Screenshots**

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Tomcat/WebSphere
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6-20200909.154756

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by alisihab**
Fixes #1058

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/jdbc/DirectQuerySender.java [hunk 1]
```diff
@@ -49,7 +50,7 @@ public void configure() throws ConfigurationException {
 	public void configure(boolean trust) throws ConfigurationException {
 		super.configure();
 		if (!trust) {
-			ConfigurationWarnings.add(log, "The class ["+getClass().getName()+"] is used one or more times. Please change to ["+FixedQuerySender.class.getName()+"] to avoid potential SQL injections!");
+			ConfigurationWarnings.add(log, "The class ["+ClassUtils.nameOf(this)+"] is used one or more times. Please change to ["+FixedQuerySender.class.getName()+"] to avoid potential SQL injections!");
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/jdbc/DirectQuerySender.java:53]: Is it also possible to add the adapter name?

File: core/src/main/java/nl/nn/adapterframework/batch/StreamTransformerPipe.java [hunk 2]
```diff
@@ -68,6 +68,7 @@
 public class StreamTransformerPipe extends FixedForwardPipe {
 
 	public static final String originalBlockKey="originalBlock";
+	private final String deprecationSuppressKey="warnings.suppress.deprecated";
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/batch/StreamTransformerPipe.java:71]: Move this, as public final static, to ConfigurationWarnings so all warnings/keys are in 1 place.

**Review by nielsm5 — CHANGES_REQUESTED** [review]

File: core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationWarnings.java [hunk 3]
```diff
@@ -32,6 +33,9 @@
 public final class ConfigurationWarnings extends BaseConfigurationWarnings {
 	private static ConfigurationWarnings self = null;
 	private Configuration activeConfiguration = null;
+	public static final String sqlInjectionSuppressKey = "warnings.suppress.sqlInjections";
+	public static final String deprecationSuppressKey="warnings.suppress.deprecated";
+	public static final String defaultValueSuppressKey = "warnings.suppress.defaultvalue";
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/configuration/ConfigurationWarnings.java:38]: Technically, final statics field names should be all uppercase

**Review by nielsm5 — CHANGES_REQUESTED** [review]

**Review by nielsm5 — APPROVED** [review]

**Review by gvanbrakel — APPROVED** [review]
