### PR TITLE
Display sender storage icons in collapsed adapter view

### LINKED ISSUE #3031: Not all expected counters shown on status page
**Describe the issue**
When running Frank2Example3/configurations/Example3/Configuration.xml I see only one blue envelope on the overview page while more IbisStore related counters are available

**Reporter**
Jaco de Groot

**To Reproduce**
See screenshots...

**Screenshots**
See blue envelope:
image
When you open adapter 01 and 02 you see they have a blue envelope available too:
image

**Configuration**
https://github.com/ibissource/frank-runner/blob/master/examples/Frank2Example3/configurations/Example3/Configuration.xml

**Input**
```
\-
```

**Environment**
```
FF! 7.8-20220407.104516: Frank2Example4
Running on xxx using Apache Tomcat/9.0.60
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 261M, total JVM memory: 587M
Free disk space: 84GB, total disk space: 475GB
Up since: 2022-04-07 17:43:01 (1h) 
```

**Additional Environment**
\-

**Additional Context**
\-

### LINKED ISSUE #3052: Title "Browse messages in state [Done]" not correct for MessageStoreSender
**Describe the issue**
When you click the small blue envelope for a MessageStoreSender the page will show:

Browse messages in state [Done] of pipe [Send] of adapter [02 RR receiving adapter with message store sender]

But this page is not showing the successfully sent messages but the messages that still need to be processed by the MessageStoreListener.

In case of no errors this page is empty. Only in case the MessageStoreListener is not reading messages this page will show the messages that are still to be picked up by the MessageStoreListener.

**Reporter**
Jaco de Groot

**To Reproduce**
1. Start Frank2Example3
2. Stop adapter 03
3. Send a message with adapter 01 (using test a pipeline)
4. Click the small blue envelop of adapter 02
5. See one message on this page
6. Start adapter 03
7. Click the small blue envelop of adapter 02
8. See zero messages on this page while the title says it is showing messages in state Done

**Screenshots**
\-

**Configuration**
See Frank2Example3

**Input**
\-

**Environment**
```
FF! 7.8-20220412.153621: Frank2Example3
Running on xxx using Apache Tomcat/9.0.60
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 181M, total JVM memory: 652M
Free disk space: 84GB, total disk space: 475GB
Up since: 2022-04-12 19:23:32 (6m) 
```

**Additional Environment**
\-

**Additional Context**
\-

### PR DESCRIPTION
**Pull request by alisihab**
Closes #3052, Closes #3031

### CODE REVIEW

**Review by nielsm5 — APPROVED** [review]

File: core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowConfigurationStatus.java [hunk 1]
```diff
@@ -510,6 +510,7 @@ private ArrayList<Object> mapAdapterPipes(Adapter adapter) {
 				} else if(sender instanceof ITransactionalStorage) { // in case no message log specified
 					ITransactionalStorage<?> store = (ITransactionalStorage<?>) sender;
 					mapPipeMessageLog(store, pipesInfo);
+					pipesInfo.put("messageStoreSender", true);
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/webcontrol/api/ShowConfigurationStatus.java:513]: At this stage it is an assumption that the transactionalStorager is part of a messageStoreSender.
It would be better to call this property 'hasTransactionalStorage'.

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

**Review by gvanbrakel — APPROVED** [review]
