### PR TITLE
Do not normalize new lines in attributes during config loading

### LINKED ISSUE #1061: NewLine not added in XsltPipe with xpathExpression
**Describe the bug**
When using an XsltPipe with an xpathExpression to concatenate strings with a newline using &#xA; the newline is not added. This happens because somewhere going from the original configuration to the loaded configuration, the &#xA; is lost. In 7.5-RC4 this does not happen.

Workaround for now is to use an .xsl.

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Framework

**To Reproduce**
1. Load the attached adapter in 7.5-RC4
2. Use test a pipeline to send <dummy/> to the adapter
3. See a response with new lines
4. Load the adapter in 7.6 snapshot
5. Repeat the test
6. See response without newlines
7. See Loaded configuration for missing newline.

**Expected behavior**
The newline not being replaced.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): Tomcat
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6-20200909.154756

**Additional context**
[ConfigurationXMLnl.zip](https://github.com/ibissource/iaf/files/5223906/ConfigurationXMLnl.zip)

### PR DESCRIPTION
**Pull request by alisihab**
Fixes #1061

### CODE REVIEW

File: core/src/test/java/nl/nn/adapterframework/xml/XmlWriterTest.java [hunk 1]
```diff
@@ -71,4 +71,20 @@ public void testNoLexicalHandling() throws Exception {
 		assertEquals(expected,xmlWriter.toString());
 	}
 
+	@Test
+	public void testDisableOutputEscaping() throws Exception {
```
Comment (gvanbrakel) [inline core/src/test/java/nl/nn/adapterframework/xml/XmlWriterTest.java:75]: I think it would be a good idea not to introduce two new resources, but to add the ``&#xa;`` value to 'in.xml', to a element, to an attribute, to the escaped data in ``<data1>`` and to the CDATA in ``<data2>`` .
You'll also have to change quite some other resource files, but it makes the test cover more.

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

File: core/src/test/java/nl/nn/adapterframework/xml/XmlWriterTest.java [hunk 2]
```diff
@@ -20,6 +20,8 @@ public void testBasic() throws Exception {
 		String expected = input;
 		XmlWriter xmlWriter = new XmlWriter();
 		XmlUtils.parseXml(input, xmlWriter);
+		/* parseXml method will resolve new line*/
+		expected = expected.replace("newline &#10;", "newline \n").replace("&lt;LF&gt;&#xa;&lt;/LF&gt;", "&lt;LF&gt;\n&lt;/LF&gt;");
```
Comment (gvanbrakel) [inline core/src/test/java/nl/nn/adapterframework/xml/XmlWriterTest.java:24]: Should the xmlWriter really resolve the new line? I would think not!

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

**Review by gvanbrakel — APPROVED** [review]

File: core/src/main/java/nl/nn/adapterframework/xml/XmlWriter.java [hunk 3]
```diff
@@ -1,5 +1,5 @@
 /*
-   Copyright 2019 Integration Partners
+   Copyright 2019 Integration Partners, 2020 WeAreFrank!
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/xml/XmlWriter.java:2]: 2019 - 2020 WeAreFrank!

File: core/src/main/java/nl/nn/adapterframework/xml/XmlWriter.java [hunk 4]
```diff
@@ -37,22 +37,22 @@
 
 public class XmlWriter extends DefaultHandler implements LexicalHandler {
 	protected Logger log = LogUtil.getLogger(this);
-	
-	private final String DISABLE_OUTPUT_ESCAPING="javax.xml.transform.disable-output-escaping";
-	private final String ENABLE_OUTPUT_ESCAPING="javax.xml.transform.enable-output-escaping";
-	
+
+	public static final String DISABLE_OUTPUT_ESCAPING="javax.xml.transform.disable-output-escaping";
+	public static final String ENABLE_OUTPUT_ESCAPING="javax.xml.transform.enable-output-escaping";
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/xml/XmlWriter.java:42]: 👍

File: core/src/test/java/nl/nn/adapterframework/xslt/ParallelXsltTest.java [hunk 5]
```diff
@@ -119,6 +119,8 @@ protected void assertResultsAreCorrect(String expected, String actual, IPipeLine
 
 //		super.assertResultsAreCorrect(combinedExpected, actual, session);
 
+		/* Parallel sender uses toXml mehtod which escapes the new line char. In the comparison we need unescaped char.*/
```
Comment (nielsm5) [inline core/src/test/java/nl/nn/adapterframework/xslt/ParallelXsltTest.java:122]: Good comment! (maybe fix mehtod though)

File: core/src/test/java/nl/nn/adapterframework/xslt/XsltTestBase.java [hunk 6]
```diff
@@ -353,7 +353,7 @@ public void xpathAttrText() throws Exception {
 	@Test
 	public void xpathNodeXml() throws Exception {
 		String input = TestFileUtils.getTestFile("/Xslt/AnyXml/in.xml");
-		String expected = "<g attr=\"Euro € single quote ' double quote escaped &quot; \">Euro € single quote ' double quote \"</g>";
+		String expected = "<g attr=\"Euro € single quote ' double quote escaped &quot; newline escaped &#10;\">Euro € single quote ' double quote \"</g>";
```
Comment (nielsm5) [inline core/src/test/java/nl/nn/adapterframework/xslt/XsltTestBase.java:356]: A tip I can give you for next time, try to not put too many test cases in 1 junit-test. It will make it more difficult to analyse the problem. In this case you're testing the escape part so it's understandable 👍

**Review by nielsm5 — CHANGES_REQUESTED** [review]

**Comment by nielsm5** [comment]
Looks good 👍  almost there

**Review by nielsm5 — APPROVED** [review]
