### PR TITLE
Wsdl validator dynamic soap body from soap action

### LINKED ISSUE #3216: WsdlXmlInputValidator does not follow soapBody messagetype for the given soapAction defined in the wsdl
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
WsdlXmlInputValidator does not follow soapBody messagetype for the given soapAction defined in the wsdl. Currently the messagetype in the soapBody is validated against the the messagetype name given in the "soapBody" attribute. The wsdl can contain a definition for what messagetype is valid in the soapBody for a certain operation/soapAction. 

For situations where a single soap-endpoint is used to receive different types of messages, it is necessary for the validator to follow these definition in the wsdl.

**Reporter**
M. Lenterman

**To Reproduce**
1. Setup WebServiceListener and WsdlXmlInputValidator with the provided wsdl definitions ([download here](https://www.gemmaonline.nl/images/gemmaonline/8/82/Zaak_DocumentServices_1_1_02.zip)).
2. Send provided soap message to the listener.
3. Observe that <genereerZaakIdentificatie_Di02> is considered invalid because no element is expected.
4. Observe that according to the wsdl definition <genereerZaakIdentificatie_Di02> is the valid content of the soapBody for the given soapAction "http://www.egem.nl/StUF/sector/zkn/0310/genereerZaakIdentificatie_Di02".

**Screenshots**

**Configuration**
```
<Adapter name="SoapEndpointRouter_VrijeBerichten"
        active="${SoapEndpointRouter_VrijeBerichten.Active}"
        description="">

        <Receiver name="SoapEndpointRouter_VrijeBerichten">
            <WebServiceListener name="SoapEndpointRouter_VrijeBerichten" address="${address.VrijeBerichten}" soap="false"/>
        </Receiver>

        <Pipeline>
            <WsdlXmlInputValidator name="SoapValidation"
				wsdl="Common/xsd/Zaak_DocumentServices_1_1_02/zkn0310/zs-dms/zkn0310_vrijeBerichten_zs-dms.wsdl"
                >
				<Forward name="succes" path="EXIT"/>
				<Forward name="failure" path="EXIT"/>
			</WsdlXmlInputValidator>
            <Exits>
                <Exit name="EXIT" state="SUCCESS"/>
            </Exits>
        </Pipeline>
```

**Input**
```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Header/><s:Body>
      <genereerZaakIdentificatie_Di02 xmlns="http://www.egem.nl/StUF/sector/zkn/0310" xmlns:StUF="http://www.egem.nl/StUF/StUF0301" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
         <stuurgegevens>
            <StUF:berichtcode>Di02</StUF:berichtcode>
            <StUF:zender>
               <StUF:organisatie>1900</StUF:organisatie>
               <StUF:applicatie>GISVG</StUF:applicatie>
            </StUF:zender>
            <StUF:ontvanger>
               <StUF:organisatie>1900</StUF:organisatie>
               <StUF:applicatie>ZDS</StUF:applicatie>
            </StUF:ontvanger>
            <StUF:referentienummer>c72d5394-76a6-48f2-95d3-9e9b067b9331</StUF:referentienummer>
            <StUF:tijdstipBericht>20220519140800794</StUF:tijdstipBericht>
            <StUF:functie>genereerZaakidentificatie</StUF:functie>
         </stuurgegevens>
      </genereerZaakIdentificatie_Di02>
   </s:Body></s:Envelope>
```

**Environment**
```
FF! 7.8-20220518.164011: Frank2zgw
Running on LAPTOP-UKAI1A6 using Apache Tomcat/9.0.56
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 461M, total JVM memory: 883M
Free disk space: 287GB, total disk space: 464GB
Up since: 2022-05-19 13:52:36 (1h) 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

### PR DESCRIPTION
**Pull request by alisihab**
Closes #3216

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java [hunk 1]
```diff
@@ -324,13 +336,33 @@ public String toExtendedString() {
...
+			throw new ConfigurationException("Could not find WSDL: " + wsdl);
+		}
+		try {
+			definition = reader.readWSDL(wsdlLocator);
+		} catch (WSDLException e) {
+			throw new ConfigurationException("WSDLException reading WSDL or import from url: " + url, e);
+		}
+		if (wsdlLocator.getIOException() != null) {
+			throw new ConfigurationException("IOException reading WSDL or import from url: " + url, wsdlLocator.getIOException());
+		}
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java:357]: Could you move this part to configure()?

File: core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java [hunk 2]
```diff
@@ -197,8 +178,40 @@ public void configure() throws ConfigurationException {
 		super.configure();
 	}
 
+	@Override
+	protected PipeForward validate(Message messageToValidate, PipeLineSession session, boolean responseMode, String messageRoot) throws XmlValidatorException, PipeRunException, ConfigurationException {
+		String soapAction = session.get(SoapBindingConstants.SOAP_ACTION, "");
+		if(StringUtils.isNotEmpty(soapAction)) {
+			setSoapBody(getSoapBodyFromSoapAction(soapAction));
+			resetCalculatedRootValidatons();
+			configure();
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java:187]: Is the soapBody always set from soapAction? Could there be cases where the calculated root validations should not be reset?

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

File: core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java [hunk 3]
```diff
@@ -197,8 +195,44 @@ public void configure() throws ConfigurationException {
...
+	@Override
+	protected PipeForward validate(Message messageToValidate, PipeLineSession session, boolean responseMode, String messageRoot) throws XmlValidatorException, PipeRunException, ConfigurationException {
+		String soapAction = session.get(SoapBindingConstants.SOAP_ACTION, "");
+		if(StringUtils.isNotEmpty(soapAction)) {
+			String soapBodyFromSoapAction = getSoapBodyFromSoapAction(soapAction);
+			if(StringUtils.compare(getSoapBody(), soapBodyFromSoapAction) != 0) {
+				log.debug("soapBody ["+soapBodyFromSoapAction+"] is determined from soapAction ["+soapAction+"]");
+				setSoapBody(soapBodyFromSoapAction);
+				resetCalculatedRootValidatons();
+				configure();
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java:207]: This is not thread safe.
Isn't it just possible to call super.validate() with messageRoot = soapBodyFromSoapAction?

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

File: core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java [hunk 4]
```diff
@@ -197,8 +195,42 @@ public void configure() throws ConfigurationException {
 		super.configure();
 	}
 
+	@Override
+	protected PipeForward validate(Message messageToValidate, PipeLineSession session, boolean responseMode, String messageRoot) throws XmlValidatorException, PipeRunException, ConfigurationException {
+		String soapAction = session.get(SoapBindingConstants.SOAP_ACTION, "");
+		if(StringUtils.isNotEmpty(soapAction)) {
+			String soapBodyFromSoapAction = getSoapBodyFromSoapAction(soapAction);
+			if(StringUtils.compare(getSoapBody(), soapBodyFromSoapAction) != 0) {
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java:203]: I would expect that the soapBodyFromSoapAction was different for request or responseMode, or is only valid for one of them.
I also think that the compare against getSoapBody is not valid. Shouldn't that be against messageRoot?

File: core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java [hunk 5]
```diff
@@ -197,8 +195,42 @@ public void configure() throws ConfigurationException {
...
+		for (Entry<QName, Binding> binding : bindings.entrySet()) {
+			List<BindingOperation> operations = binding.getValue().getBindingOperations();
+			for (BindingOperation bindingOperation : operations) {
+				List<ExtensibilityElement> elements = bindingOperation.getExtensibilityElements();
+				if(elements != null && !elements.isEmpty()) {
+					for (ExtensibilityElement element : elements) {
+						if(element instanceof SOAPOperation) {
+							String soapActionFromDefinition = ((SOAPOperation) element).getSoapActionURI();
+							if(soapActionFromDefinition.equals(soapAction)) {
+								return bindingOperation.getName();
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java:222]: I think the soapBody element does not need to be equal to the name of the bindingOperation, is it?

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

File: core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java (hunk 5 above)
Comment (alisihab) [reply core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java]: True, the referenced element in input/output definition should be used

File: core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java [hunk 6]
```diff
@@ -197,8 +197,44 @@ public void configure() throws ConfigurationException {
...
+								javax.wsdl.Message message = responseMode ? bindingOperation.getOperation().getOutput().getMessage() : bindingOperation.getOperation().getInput().getMessage();
+								Map<String, Part> parts = message.getParts();
+								return parts.values().stream().map(Part::getElementName).map(QName::getLocalPart).collect(Collectors.joining(","));
+							}
+						}
+					}
+				}
+			}
+		}
+		return getSoapBody();
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java:233]: in responseMode, this should be outputSoapBody.
However, I think it would be better to return null if no element is found, and then to stick to the original messageRoot argument of validate()

File: core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java [hunk 7]
```diff
@@ -323,13 +358,22 @@ public String toExtendedString() {
 		return "[" + getConfigurationClassLoader() + "][" + FilenameUtils.normalize(getWsdl()) + "][" + getSoapBody() + "][" + getOutputSoapBody() + "][" + getSoapBodyNamespace() + "]";
 	}
 
-	@IbisDoc({"1", "pairs of uri references which will be added to the wsdl", " "})
+	@IbisDoc({"the wsdl to read the xsd's from", " "})
+	public void setWsdl(String wsdl) {
+		this.wsdl = wsdl;
+	}
+
+	@IbisDoc({"Name of the child element of the SOAP body, or a comma separated list of names to choose from (only one is allowed) (wsdl generator will use the first element) (use empty value to allow an empty soap body, for example to allow element x and an empty soap body use: x,). In case the request contains SOAPAction header and the wsdl contains an element specific to that SOAPAction, it will use that element as soapBody.", "" })
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/pipes/WsdlXmlValidator.java:366]:
```suggestion
	@IbisDoc({"Name of the child element of the SOAP body, or a comma separated list of names to choose from (only one is allowed) (WSDL generator will use the first element) (use empty value to allow an empty SOAP body, for example to allow element x and an empty SOAP body use: x,). In case the request contains SOAPAction header and the WSDL contains an element specific to that SOAPAction, it will use that element as SOAP body.", "" })
```

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

**Review by gvanbrakel — APPROVED** [review]
