### PR TITLE
Fix determining service location in the generated wsdl

### LINKED ISSUE #1798: Determine 'external address of ibis' in Wsdl generation
**Describe the issue**
When a WSDL is generated, the adress that is generated is the string 'external address of ibis'. This should contain the real external address of the ibis, or contain at least the right context path.

**Reporter**
Gerrit

**To Reproduce**
1. Go to iaf-test -> Webservices -> Available WSDL's -> Soapvalidator
2. Click on WSDL
3. See that the soap port contains the line: `<soap:address location="external address of ibis"/>`

**Screenshots**

**Configuration**
```
```

**Input**
```
```

**Environment**
```
FF! 7.7-20210505.130333: Ibis4Test
Running on srdzzapp0455 using IBM WebSphere Application Server/9.0.5.7
Java Version: Java(TM) SE Runtime Environment (8.0.6.26 - pxa6480sr6fp26-20210216_01(SR6 FP26))
Heap size: 407M, total JVM memory: 512M
Free disk space: 1GB, total disk space: 2GB
Up since: 2021-05-10 17:46:41 (42m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

### PR DESCRIPTION
**Pull request by alisihab**
Closes #1798

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/webcontrol/api/Webservices.java [hunk 1]
```diff
@@ -212,6 +212,31 @@ public void write(OutputStream out) throws IOException, WebApplicationException
...
+			if(listener instanceof WebServiceListener) {
+				String address = ((WebServiceListener) listener).getAddress();
+				String serviceNameSpaceUri = ((WebServiceListener) listener).getServiceNamespaceURI();
+				if(StringUtils.isNotEmpty(address)) {
+					endpoint = address;
+				} else if(StringUtils.isNotEmpty(serviceNameSpaceUri)) {
+					endpoint=serviceNameSpaceUri;
+				} else {
+					endpoint=listener.getName();
+				}
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/webcontrol/api/Webservices.java:229]: Routing based on the namespace uri doesn't mean the uri is the external address.
If no address has been provided, the endpoint should be `services/rpcrouter`.
See NamespaceUriProvider and NamespaceUriProviderBean

**Review by nielsm5 — CHANGES_REQUESTED** [review]

**Review by nielsm5 — APPROVED** [review]

**Review by gvanbrakel — APPROVED** [review]
