### PR TITLE
Fix #1892 exception pipe should not follow exception forward

### LINKED ISSUE #1892: Global-forward exception creates infinite loop with ExceptionPipe
**Describe the issue**
When having a global forward with name exception and a path to an ExceptionPipe, an infinite loop is created in 7.6 and 7.7 when the exception global forward is used, this does not happen in 7.5.

**Reporter**
Ricardo

**To Reproduce**
1. Load the configuration from below
2. Use Test a Pipeline to send a message to the adapter
3. Open Ladybug and open the running report
4. See ExceptionPipe being hit over and over again
5. Get OutOfMemoryException in Test a Pipeline after some time

**Screenshots**

**Configuration**
```
<module>
	<adapter name="Repro3" description="Repro3">
		<receiver name="Repro3"
			className="nl.nn.adapterframework.receivers.GenericReceiver">
			<listener name="Repro3" className="nl.nn.adapterframework.receivers.JavaListener"/>
		</receiver>

		<pipeline firstPipe="Exception">

			<exits>
				<exit path="READY" state="success"/>
				<exit path="FAILED" state="failure"/>
			</exits>

			<global-forwards>
				<forward name="exception" path="Exception"/>
				<forward name="failure" path="Exception"/>
				<forward name="error" path="Exception"/>
			</global-forwards>

			<pipe name="Exception" className="nl.nn.adapterframework.pipes.ExceptionPipe">
				<forward name="success" path="READY"/>
			</pipe>
		</pipeline>
	</adapter>
</module>
```

**Input**
```
<test/>
```

**Environment**
```
FF! 7.7-20210608.182006: ibis4repro
Running on LPZWNL000014943 using Apache Tomcat/9.0.39
Java Version: OpenJDK Runtime Environment (1.8.0_252-b09)
Heap size: 663M, total JVM memory: 910M
Free disk space: 71GB, total disk space: 237GB
Up since: 2021-06-09 14:13:54 (3m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]: N/A
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]: N/A

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

### PR DESCRIPTION
**Pull request by alisihab**
Closes #1892

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/http/rest/ApiPrincipalPipe.java [hunk 1]
```diff
@@ -127,7 +128,7 @@ public PipeRunResult doPipe(Message message, PipeLineSession session) throws Pip
 			return new PipeRunResult(getSuccessForward(), "");
 		}
 
-		return new PipeRunResult(findForward("exception"), "this is not supposed to happen... like ever!");
+		return new PipeRunResult(findForward(PipeForward.EXCEPTION_FORWARD_NAME), "this is not supposed to happen... like ever!");
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/http/rest/ApiPrincipalPipe.java:131]: zinloze foutmelding,

**Review by gvanbrakel — APPROVED** [review]

**Review by gvanbrakel — APPROVED** [review]

**Review by nielsm5 — APPROVED** [review]
