### PR TITLE
Fix import for stylesheets in error message formatter

### LINKED ISSUE #3241: ErrorMessage formatter fails to load include of stylesheet
**Describe the issue**
While formatting an error message using a stylesheet, the application hangs in initializing a stylesheet, or in initializing an include of the stylesheet.

**Reporter**
Biplab

**To Reproduce**

**Configuration**
```
<errorMessageFormatter className="nl.nn.adapterframework.errormessageformatters.FixedErrorMessage"                             styleSheetName="CheckSetPortalMutation/xsl/InternalErrorRLY.xsl"/>
```

**Input**
stylesheet: [InternalErrorRLY.xsl.txt](https://github.com/ibissource/iaf/files/8754577/InternalErrorRLY.xsl.txt)

**Environment**
```
FF! 7.7.1: Ibis4Baco
Running on xxxx using IBM WebSphere Application Server/9.0.5.10
Java Version: Java(TM) SE Runtime Environment (8.0.7.0 - pxa6480sr7-20211025_01(SR7))
Heap size: 1586M, total JVM memory: 2048M
Free disk space: 1GB, total disk space: 2GB
Up since: 2022-05-20 17:38:50 (2d)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
error logging:
```
[23-5-22 12:11:22:324 CEST] 00000092 TimeoutManage I WTRN0006W: Transaction 00000180F02F6FD30000000108B305E0DE5F37C28BEB7171C516979AF9002C0FE285C09D00000180F02F6FD30000000108B305E0DE5F37C28BEB7171C516979AF9002C0FE285C09D00000001 has timed out after 3600 seconds.
[23-5-22 12:11:22:327 CEST] 00000092 TimeoutManage I WTRN0124I: When the timeout occurred the thread with which the transaction is, or was most recently, associated was Thread[HandleGPAMessage JdbcQueryListener-listener[18],5,ControlTasks]. The stack trace of this thread when the timeout occurred was:
      org.apache.xml.utils.URI.initialize(URI.java:562)
      org.apache.xml.utils.URI.<init>(URI.java:196)
      org.apache.xml.utils.SystemIDResolver.getAbsoluteURI(SystemIDResolver.java:285)
      org.apache.xalan.processor.ProcessorInclude.getBaseURIOfIncludedStylesheet(ProcessorInclude.java:390)
      org.apache.xalan.processor.ProcessorInclude.startElement(ProcessorInclude.java:137)
      org.apache.xalan.processor.StylesheetHandler.startElement(StylesheetHandler.java:623)
      org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
      org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
      org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
      org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
      org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
      org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
      org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
      org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
      org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
      org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
      org.apache.xalan.processor.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:917)
      org.apache.xalan.processor.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:771)
      nl.nn.adapterframework.util.XmlUtils.createTransformer(XmlUtils.java:1047)
      nl.nn.adapterframework.util.XmlUtils.createTransformer(XmlUtils.java:1037)
      nl.nn.adapterframework.util.XmlUtils.createTransformer(XmlUtils.java:1026)
      nl.nn.adapterframework.errormessageformatters.FixedErrorMessageFormatter.format(FixedErrorMessageFormatter.java:77)
      nl.nn.adapterframework.core.Adapter.formatErrorMessage(Adapter.java:346)
      nl.nn.adapterframework.receivers.Receiver.processMessageInAdapter(Receiver.java:1336)
      nl.nn.adapterframework.receivers.Receiver.processRequest(Receiver.java:1015)
      nl.nn.adapterframework.receivers.JavaListener.processRequest(JavaListener.java:156)
      nl.nn.adapterframework.senders.IbisLocalSender.sendMessage(IbisLocalSender.java:237)
```

### PR DESCRIPTION
**Pull request by alisihab**
Closes #3241

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/errormessageformatters/XslErrorMessageFormatter.java [hunk 1]
```diff
@@ -60,45 +64,40 @@ public Message format(String errorMessage, Throwable t, INamedObject location, M
...
-				}
-				else {
-					String xpath = getXpathExpression();
-//					if (StringUtils.isEmpty(xpath)) {
-//						xpath="/errorMessage/@message";
-//					}
-					errorTransformer = XmlUtils.createTransformer(XmlUtils.createXPathEvaluatorSource(xpath));
+					URL url = ClassUtils.getResourceURL(this, getStyleSheet());
+					int xsltVersion = XmlUtils.detectXsltVersion(url);
+					errorTransformer = XmlUtils.createTransformer(new StreamSource(url.openStream()), xsltVersion, new ClassLoaderURIResolver(this));
```
Comment (nielsm5) [inline core/src/main/java/nl/nn/adapterframework/errormessageformatters/XslErrorMessageFormatter.java:69]: It might be better to use a Resource here. It will also set the systemId, reads from the url (with the correct resolver). The only thing I'm not sure about is if the transformerpool uses the SaxSource resourceResolver

File: core/src/main/java/nl/nn/adapterframework/errormessageformatters/XslErrorMessageFormatter.java [hunk 2]
```diff
@@ -57,48 +57,39 @@ public Message format(String errorMessage, Throwable t, INamedObject location, M
...
-				else {
-					String xpath = getXpathExpression();
-//					if (StringUtils.isEmpty(xpath)) {
-//						xpath="/errorMessage/@message";
-//					}
-					errorTransformer = XmlUtils.createTransformer(XmlUtils.createXPathEvaluatorSource(xpath));
+					Resource xsltSource = Resource.getResource(this, getStyleSheet());
+					transformerPool = TransformerPool.getInstance(xsltSource, 0);
+				} else {
+					transformerPool = TransformerPool.getXPathTransformerPool(null, getXpathExpression(), null, false, getParameterList());
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/errormessageformatters/XslErrorMessageFormatter.java:66]: I think this code can be further simplified by using TransformerPool.configureTransformer()

**Review by gvanbrakel — APPROVED** [review]

**Review by nielsm5 — APPROVED** [review]
