### PR TITLE
Limit eligibility to have wsdl

### LINKED ISSUE #1463: ApiListener results in being listed with error message on webservices page
**Describe the bug**
When having an adapter with only ApiListeners and an InputValidator a message is shown for that adapter in the WSDL section of the webservices page: "Adapter has an inputValidator using the schema attribute in which case a WebServiceListener with serviceNamespaceURI is required"

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Console
 - Frank Framework

**To Reproduce**
1. Have an adapter with an ApiListener in its receiver and an inputValidator with a schema defined
2. Load the adapter
3. Go to the webservices page in the Ibis
4. See message

**Expected behavior**
The adapters not being listed with such a strange message, or maybe even not listed at all here. Not listing them might also apply to adapters that only have JavaListeners without an inputValidator.

**Screenshots**
N/A

**Environment:**
 - Application server: [e.g. Tomcat/WebSphere/JBOSS/Jetty]: Tomcat/Websphere
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql,PostgreSQL]: Oracle
 - Browser: [e.g. Chrome, Safari, Edge]: Chrome
 - IAF Version: [e.g. 7.5, 7.6]: 7.6-20210210.135504

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by alisihab**
Closes #1463

### CODE REVIEW

File: core/src/main/java/nl/nn/adapterframework/soap/WsdlUtils.java [hunk 1]
```diff
@@ -120,4 +123,16 @@ static String validUri(String uri) {
         return uri == null ? null : uri.replaceAll(" ", "_");
     }
 
+    //check if the adapter has an WebServiceListener with an inputValidator 
+	public static boolean canHaveWsdl(Adapter adapter) {
+		IValidator inputValidator = adapter.getPipeLine().getInputValidator();
+		boolean haveWebServiceListener = false;
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/soap/WsdlUtils.java:129]: correct English would be 'hasWebServiceListener'

File: core/src/main/java/nl/nn/adapterframework/webcontrol/api/Webservices.java [hunk 2]
```diff
@@ -95,11 +96,14 @@ public Response getLogDirectory() throws ApiException {
...
 		for (Adapter adapter : getIbisManager().getRegisteredAdapters()) {
-			Map<String, Object> wsdlMap = new HashMap<String, Object>(2);
+			Map<String, Object> wsdlMap = null;
 			try {
-				Wsdl wsdl = new Wsdl(adapter.getPipeLine());
-				wsdlMap.put("name", wsdl.getName());
-				wsdlMap.put("extension", getWsdlExtension());
+				if(WsdlUtils.canHaveWsdl(adapter)) { // check eligibility
+					wsdlMap = new HashMap<String, Object>(2);
+					Wsdl wsdl = new Wsdl(adapter.getPipeLine());
```
Comment (gvanbrakel) [inline core/src/main/java/nl/nn/adapterframework/webcontrol/api/Webservices.java:103]: I think it is wise to add a TODO comment here, stating that Wsdl generation should be done on demand, not beforehand.

**Review by gvanbrakel — CHANGES_REQUESTED** [review]

**Review by gvanbrakel — DISMISSED** [review]

**Review by gvanbrakel — APPROVED** [review]
It appeared that I caused the Wsdl errors myself. Sorry for accusing you...
They have been fixed anyway!

**Review by nielsm5 — APPROVED** [review]
